//go:build e2e_realclaude

package realclaude

// #1941 — the write half of the AskUserQuestion capture: the writer that puts
// #1943's record on disk under the name #1944's namer mints, into a directory
// its caller chooses, the fail-closed deny-scan that refuses the record BEFORE
// the first filesystem call, and the offline round trip proving no field is
// dropped on the way.
//
// A measurement whose only trace is a test log evaporates when the run ends, so
// the committed artifact is the point — and an artifact is worth committing only
// if it is COMPLETE (no field silently dropped on the way to disk), ATOMIC (no
// half-written residue stranded for a later commit) and SCAN-CLEAN (its
// marshalled bytes carry no value of an armed deny class). None of the three
// needs a claude binary. This file settles all three.
//
// The scan is the load-bearing half and it is EVIDENCE-BASED rather than
// hypothetical. Re-measured against main on 2026-09-01, twelve of the seventeen
// captures committed under testdata/ carry at least one deny-class occurrence:
// /Users/ in initialize_control_v2.1.239.json and in each of the four
// set_permission_mode_v2.1.220_* captures, /var/folders/ in seven of the eight
// permission_protocol_* ones and in all four set_permission_mode_* ones. Once
// committed, those bytes are permanent — #1688's whole-stream capture needed
// three follow-up tickets (#1729, #1732, #1733) to redact what it had already
// swallowed.
//
// The scan is the writer's PRECONDITION, not an add-on, and the two land in one
// commit deliberately. The sibling family shipped its writer in #1702 and
// retrofitted the scan in #1748, which cost that ticket a restructure of shipped
// code and left one merge window with an unguarded writer.
//
// # What this file deliberately is not
//
// It adds no field to askQuestionFixtureRecord and mints no second fixture —
// both are #1943's, and this file reads them. It mints no filename — that is
// #1944's, and this file calls it. It has NO FILL SITE: askQuestionFullRecord's
// doc comment forward-references "#1941's fill site is where the two fields are
// minted from one call", which was written before this ticket was refined and is
// STALE. This slice is offline and mints nothing from a live call; the fill site
// is #1938's. Do not build one here to satisfy that sentence, and do
// not edit it here either — the comment is #1943's and correcting it belongs
// with the slice that actually builds the thing it describes.
//
// The per-class sweep over every armed class is not here either. That was its
// own ticket for the sibling family (#1749); AC 2 asks for two planted rows.
//
// # What the round trip catches, and what it cannot
//
// The read-back decodes through the struct that wrote the file, so it is
// symmetric and CANNOT catch a misspelled JSON tag. #1662's code review
// sharpened that limit: even a UNIQUE wrong tag round-trips green, because only
// a COLLIDING tag makes encoding/json drop both. Applying askQuestionFixtureFields
// to both sides does not change it — the listing labels failure messages here
// rather than checking anything. The instrument is a reviewer diffing #1943's
// hand-written listing against the struct's tags, which is why that listing must
// never be regenerated by reflection.
//
// # Offline, and the one ban this file must not copy from its two siblings
//
// This file reaches no live claude, no daemon, no subprocess and no credential:
// it must not reach resolveClaudeBin, probeClaudeVersion, WithWorktree,
// WithWorktreeAuthenticated or captureClaudeVersion, nor os.Getenv, os.Environ
// or os.LookupEnv, nor packageDir or any of the wrappers setModeFixturePath,
// writeSetModeFixture and writeFixture that resolve the committed testdata/
// through it, nor newDropcapScanner or realHome.
//
// It DOES write, read back and list a directory — that is its entire subject —
// so unlike ask_user_question_record_test.go and ask_user_question_names_test.go
// it bans none of the os read/write helpers. The relative-path hazard those bans
// close for the two files that perform no I/O — `go test` runs in the package
// source directory, so a RELATIVE os.WriteFile("testdata/…") reaches the
// committed captures without naming packageDir at all — is closed here instead
// by the exactly-one-entry assertion below: bytes that escaped to a relative
// testdata/ leave the t.TempDir() holding ZERO entries.
//
// TestFinOfflineFilesReachNoExecHelper enforces the ban over this file's AST
// rather than over this paragraph — it parses without parser.ParseComments
// precisely so the check cannot answer itself out of the sentence that states
// it.
//
//	go test -tags e2e_realclaude -race -count=1 -v \
//	  -run 'TestAskQuestionFixture_|TestFinOfflineFilesReachNoExecHelper' \
//	  ./internal/e2e/realclaude/
//
// Both must report PASS — not SKIP, not "no tests to run" — on a machine with no
// claude and no credentials. Read the count of tests that executed, never the
// exit code: this package is behind the e2e_realclaude tag, `make check` never
// compiles it, and the suite exits 0 both on a build failure and on a full
// credentials skip. `make preship` is the gate that proves the package builds.

import (
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

// --- the fail-closed scan -------------------------------------------------------

// scanAskQuestionFixture returns the exact bytes writeAskQuestionFixture will put
// on disk, refusing the record outright when the deny-scan hits.
//
// IT MAKES NO FILESYSTEM CALL OF ANY KIND, AND ITS SIGNATURE CARRIES NO
// DIRECTORY. That absence is the mechanism behind AC 2 rather than a coincidence
// of layout: a function with no path parameter cannot create an entry under one
// even in principle. This step is also the sole producer of the bytes the writer
// puts on disk and the scan is INSIDE it, so the writer cannot hold a blob the
// scan has not passed; and the first filesystem call anywhere on the path is the
// writer's os.MkdirAll, strictly after this returns. A hit therefore leaves the
// target directory holding nothing — no record, no .tmp under any name, nothing
// written and then deleted. That claim has no seam to observe it from (a hit is a
// t.Fatalf that takes the calling subtest down), so it is discharged by
// construction; its executable half is the exactly-one-entry assertion in
// TestAskQuestionFixture_RoundTripsEveryFieldIntoOneNamedEntry, which reads the
// same mechanism from the SUCCESS end.
//
// IT DOES NOT COPY THE RECORD, and that is a deliberate divergence from
// scanInitControlFixture. There is no cap to apply — this record carries no
// capture field — so `out := *rec` would be a defensive-LOOKING shallow copy that
// mutates nothing while sharing ToolInput's backing array with the caller. The
// caller's pointer is marshalled directly. A future field cap must add the copy
// AND reckon with the slice field rather than inheriting a copy that already
// looks safe: a cap scoped to json.RawMessage writes through the caller's array
// from behind exactly such a copy.
//
// SCAN'S SECOND RETURN IS DISCARDED, and the reason is measured rather than
// stylistic. Do NOT extend the refusal to notApplied. newDropcapScanner arms
// CLAUDE_CODE_OAUTH_TOKEN and ANTHROPIC_API_KEY through os.Getenv; on a
// subscription-login machine both are unset, scan classes an empty dynamic needle
// as not-applied, and a writer refusing on notApplied would refuse EVERY live
// capture #1938 attempts. The vacuity control in
// TestAskQuestionFixture_ScanRefusesAPlantedValue is where notApplied is
// consumed, and that is the right place: offline, over a fixed-only scanner,
// where a non-empty list means a fixed needle was wrongly marked dynamic.
//
// # The refusal, and the two rules that bind every line added here
//
// On a hit: t.Fatalf naming the COUNT and the CLASS NAMES and nothing else. No
// excerpt, no record dump, no needle value, no byte offset. "Let me include the
// payload to help debug it" is exactly how a token reaches a salvaged run log and
// inverts the whole control. There is no fake testing.TB in this package and
// testing.TB cannot be implemented outside testing, so no row observes what this
// prints; the rule is the guard.
//
// NEVER FORMAT THE SCANNER. newDropcapScanner stores CLAUDE_CODE_OAUTH_TOKEN and
// ANTHROPIC_API_KEY as needle VALUES, so a dropcapScanner in scope is two live
// credentials in a struct — no %v, %+v, %#v or %q on the scanner, on a needle or
// on the needle slice, here or in the writer or in any row added later.
//
// t.Fatalf requires the test goroutine. This step and the writer are both called
// directly from one, so t.Helper() plus a direct call is the whole discipline. Do
// not call either from a goroutine — including from #1938's stdout reader.
func scanAskQuestionFixture(t *testing.T, scanner dropcapScanner, rec *askQuestionFixtureRecord) []byte {
	t.Helper()

	data, err := json.MarshalIndent(rec, "", "  ")
	if err != nil {
		// The one message here carrying text this file did not author.
		// encoding/json reports an invalid json.RawMessage by naming the offending
		// character rather than by echoing the payload, so %v on it is bounded —
		// a judgment about a bounded error string, not a licence to widen the set.
		t.Fatalf("#1941: marshal fixture for claude_version_slug %q tool_name %q: %v",
			rec.ClaudeVersionSlug, rec.ToolName, err)
	}
	hits, _ := scanner.scan(data)
	if len(hits) > 0 {
		t.Fatalf("#1941: deny-scan found %d denied class(es) in the AskUserQuestion fixture for "+
			"claude_version_slug %q tool_name %q: %v\nNOTHING was written — no record, no .tmp, "+
			"nothing under the target directory at all. Redact the named class at the capture "+
			"site and re-run. The offending value is deliberately not printed, and neither is "+
			"its offset: putting either in a run log this pipeline salvages is exactly the "+
			"exposure this scan exists to prevent",
			len(hits), rec.ClaudeVersionSlug, rec.ToolName, hits)
	}
	return data
}

// --- the writer -------------------------------------------------------------------

// writeAskQuestionFixture writes rec into dir and returns the written path.
//
// dir IS A PARAMETER, DELIBERATELY — unlike writeSetModeFixture and writeFixture,
// which resolve the real testdata/ through packageDir. That is what lets this
// writer settle here against a t.TempDir(), with #1938 passing the
// committed directory later. os.MkdirAll is a no-op against a t.TempDir() and
// against the committed directory alike, and is kept for the sibling writer's
// reason: a live slice's directory may not exist.
//
// The bytes come from scanAskQuestionFixture and are written BYTE FOR BYTE, with
// nothing appended — not even a trailing newline, which would break the
// read-back's field equality by one byte. That step marshals and runs the
// deny-scan and touches the filesystem not at all, so the first filesystem call
// on this path is the os.MkdirAll below and a refused record strands nothing
// under dir.
//
// THE NAME IS MINTED, NEVER FORMATTED. askQuestionFixtureName owns both the
// ask_user_question_v prefix and the slug column. A writer interpolating its own
// "ask_user_question_v%s.json" reopens the overwrite and containment hazards
// #1944's lock exists to close, with #1944's own tests still green.
//
// FEED IT ClaudeVersionSlug, NEVER ClaudeVersionRaw. This record carries no bare
// version token: the raw field is a whole `claude --version` line, which slugs to
// something else entirely. #1944's lock already pins the row this satisfies —
// token 2.1.239-fixture mints ask_user_question_v2.1.239-fixture.json, slug-clean
// by construction so re-slugging it is a fixed point.
//
// NAME CONTAINMENT IS INHERITED FROM THE NAMER, and that is the security-relevant
// reason not to format the name here. versionSlug maps every byte outside
// [a-z0-9._-] to _, so no path separator survives its input, and the literal
// prefix — which no input can reach — means the minted name can never be "." or
// "..". filepath.Join therefore cannot escape dir however odd the version token
// is. That guarantee is LEXICAL and says nothing about dir itself: pass a
// directory that is or contains a symlink and the write still resolves wherever
// it points. Choosing dir stays the caller's responsibility.
//
// THE SCANNER IS A PARAMETER, the way dir already is, and NEVER a
// newDropcapScanner call in this file. That constructor reads os.Getenv twice and
// realHome, so a table built through it is green or red depending on whose
// machine ran it — and this file's finOfflineExecBans entry bans all four names
// precisely because the check is an AST identifier match: calling the constructor
// here would satisfy the os.Getenv ban to the letter while destroying the offline
// property it protects. Both offline callers pass
// dropcapScanner{needles: dropcapFixedNeedles()}, written inline at the call site.
// NEVER FORMAT THE SCANNER: see scanAskQuestionFixture's doc.
//
// THIS WRITER IS THE ONLY SANCTIONED ROUTE TO A COMMITTED AskUserQuestion
// ARTIFACT, and the scan is BYPASSABLE BY CONSTRUCTION: a caller that marshals
// the record and calls os.WriteFile itself never reaches the step, and nothing in
// this slice can detect that — finOfflineExecBans is per-file, and #1938's live
// capture file execs, so it can never carry an entry. Addressed to it: a direct
// marshal-and-write of this record is the defect to look for at review, and it is
// the one failure mode this net cannot see.
//
// THE .tmp NAME IS DERIVED FROM THE TARGET NAME, so two writers minting the same
// name into one directory race on it. The two offline callers here cannot collide
// — one writes once, the other writes nothing — but a live slice that ever writes
// twice must give each write its own directory.
//
// Failure is always t.Fatalf naming claude_version_slug and the error and NOTHING
// ELSE: a %+v of the record would move claude-supplied tool_input bytes out of the
// scanned, committed artifact and into an unbounded run log. That field is the
// leak surface the whole scan exists for. claude_version_slug is safe for the
// reason it is already half the filename.
func writeAskQuestionFixture(t *testing.T, dir string, scanner dropcapScanner, rec *askQuestionFixtureRecord) string {
	t.Helper()

	// FIRST, and before any filesystem call: a refused record must strand nothing
	// under dir, not even a .tmp.
	data := scanAskQuestionFixture(t, scanner, rec)

	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("#1941: mkdir fixture dir for claude_version_slug %q: %v",
			rec.ClaudeVersionSlug, err)
	}
	path := filepath.Join(dir, askQuestionFixtureName(rec.ClaudeVersionSlug))
	// Temp file and rename, the discipline every writer in this package uses: an
	// interrupted run must not strand a half-written fixture under the target name
	// for a later commit.
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o644); err != nil {
		t.Fatalf("#1941: write fixture tmp for claude_version_slug %q: %v",
			rec.ClaudeVersionSlug, err)
	}
	if err := os.Rename(tmp, path); err != nil {
		t.Fatalf("#1941: rename fixture for claude_version_slug %q: %v",
			rec.ClaudeVersionSlug, err)
	}
	return path
}

// --- the planted values -------------------------------------------------------

// askQuestionPlantedPath is the synthetic operator path one refusal row plants,
// and askQuestionPlantedKeyPrefix the synthetic credential the other does. Both
// are FIXED deny classes — /Users/ and sk-ant- — armed on every scanner and
// exempt from dropcapMinNeedle by construction, so neither has a minimum length
// to satisfy. Do NOT import that constraint from newInitControlOfflineScanner's
// constant block, which arms DYNAMIC needles and therefore does have it: the
// two credential-VARIABLE classes belong to newDropcapScanner's dynamic half and
// to the live run, not here, which is why the credential row below plants a
// PREFIX rather than a token value.
//
// Three constraints bind both literals, and each changes what its row proves:
//
//   - ONE ARMED CLASS EACH. askQuestionPlantedPath carries no /home/, no
//     /var/folders/, no /private/var/folders/ and no sk-ant-;
//     askQuestionPlantedKeyPrefix carries no path of an armed class. A plant
//     carrying two classes makes its row pass for the wrong reason and stops
//     being the sole red for its own.
//   - JSON-STRING-SAFE: no '"' and no '\'. askQuestionPlantedInput splices the
//     value into a string literal rather than marshalling it, so a quote there
//     produces invalid JSON and the row reports a marshal error instead of a
//     scan verdict.
//   - NO '<', '>' OR '&', matching askQuestionFixtureInput's own constraint.
//     scan checks both the raw and the JSON-escaped spelling of every needle, so
//     such a character would not defeat the row — it would introduce a SECOND,
//     unrelated difference between the two spellings and muddy what the row is
//     about.
//
// The credential value's tail must read as unmistakably not-a-key to a human and
// to a secret scanner. This is the sibling's spelling, and that spelling's
// presence on main is what establishes that this repo's push protection does not
// block the shape.
const (
	askQuestionPlantedPath      = "/Users/synthetic-operator/Library/Logs/ask-user-question.log"
	askQuestionPlantedKeyPrefix = "sk-ant-synthetic-not-a-real-key"
)

// askQuestionPlantedInput returns an AskUserQuestion-shaped input carrying plant
// inside one JSON string value.
//
// TOOL_INPUT IS THE CARRIER FOR BOTH PLANTS, and the reason is structural rather
// than convenient: it is the ONLY field whose bytes come from the child.
// claude_version_raw and claude_version_slug are minted from `claude --version`
// and tool_name is a constant, so a leak arriving through any of the three is not
// a scenario this net exists for. That also puts the rows in the one field the
// record exists to carry.
//
// It is deliberately not askQuestionFixtureInput with a value appended: that
// literal's key ordering is #1943's wire-order instrument, and a helper that
// edited it would couple these rows to a property that is not theirs. The shape
// here is its own, smaller literal — one question, one option — and nothing
// asserts over its key order.
func askQuestionPlantedInput(plant string) json.RawMessage {
	return json.RawMessage(`{"questions":[{"header":"Scope-FIXTURE",` +
		`"question":"Which synthetic -FIXTURE path should this change touch, given ` + plant + `?",` +
		`"multiSelect":false,` +
		`"options":[{"label":"internal/sessions-FIXTURE","description":"the session pool"}]}]}`)
}

// --- the round trip -----------------------------------------------------------

// TestAskQuestionFixture_RoundTripsEveryFieldIntoOneNamedEntry is #1941's AC 1
// and AC 4, plus the SUCCESS-PATH half of AC 2: every field of #1943's
// fully-populated record survives write-then-read-back, the raw-JSON tool_input
// included, and the target directory afterwards holds exactly one entry, named
// exactly what askQuestionFixtureName mints from the record's own
// claude_version_slug.
//
// The subtest shares the written artifact with the assertions after it and is
// deliberately NOT parallel; the parent owns the tempdir.
//
// It does not restate #1943's properties. Non-zero, same-typed distinctness and
// the slug shape ship in TestAskQuestionFullRecord_PinsTheFourFieldsAndTheSlugShape
// and are preconditions this test consumes rather than assertions it repeats.
//
// TWO LIMITS, STATED RATHER THAN CLAIMED AWAY:
//
//   - The round trip cannot catch a misspelled JSON tag, for the reason this
//     file's header gives at length. The listing labels failure messages here.
//   - The name assertion is 0-RED ON THE SLUG COLUMN. claude_version_slug is
//     slug-clean by #1943's construction — that file's own fixed-point subtest
//     pins it — so a writer interpolating "ask_user_question_v" +
//     rec.ClaudeVersionSlug + ".json", dropping the versionSlug call entirely,
//     mints the identical name and this row stays green. #1944's golden table is
//     where that mutant reddens, and this file must not claim otherwise.
func TestAskQuestionFixture_RoundTripsEveryFieldIntoOneNamedEntry(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	rec := askQuestionFullRecord()
	// The offline construction, written inline at the call site rather than behind
	// a local helper: it is one short expression, it is the spelling the sibling
	// family already uses, and inline keeps "this reads no environment" visible at
	// the site this file's finOfflineExecBans entry protects.
	path := writeAskQuestionFixture(t, dir, dropcapScanner{needles: dropcapFixedNeedles()}, rec)

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("#1941: read back the fixture for claude_version_slug %q: %v",
			rec.ClaudeVersionSlug, err)
	}
	var got askQuestionFixtureRecord
	if err := json.Unmarshal(data, &got); err != nil {
		t.Fatalf("#1941: decode the fixture for claude_version_slug %q: %v",
			rec.ClaudeVersionSlug, err)
	}

	// Normalised at this SINGLE SITE rather than through a compactInitControlRawRows
	// clone, exactly as #1943's own round trip does it: json.MarshalIndent indents
	// INSIDE an embedded raw message, so an uncompacted comparison reddens against a
	// perfectly correct writer. That helper's type switch and touched-name canary
	// exist because its record has three raw fields of two Go types; with one field
	// there is nothing for a widened normaliser to blind and nothing for a narrowed
	// one to miss that the row itself would not report.
	wantRec := *rec
	wantRec.ToolInput = compactRawMessages(t, []json.RawMessage{wantRec.ToolInput})[0]
	haveRec := got
	haveRec.ToolInput = compactRawMessages(t, []json.RawMessage{haveRec.ToolInput})[0]

	// Both sides go through the SAME listing. There is deliberately no length guard
	// before the zip: both slices come from one function over one struct type, so a
	// divergence is impossible and the guard could never redden.
	want := askQuestionFixtureFields(&wantRec)
	have := askQuestionFixtureFields(&haveRec)

	t.Run("every field survives the round trip", func(t *testing.T) {
		for i := range want {
			if !reflect.DeepEqual(want[i].value, have[i].value) {
				// Printing both values is safe HERE AND ONLY HERE: every value in
				// askQuestionFullRecord is a #1943 synthetic literal, and the
				// diagnostic is worth more than protecting a fixture string. #1938
				// fills this same record's tool_input FROM A LIVE CHILD, so a row
				// that printed it there would move claude-supplied bytes out of
				// the scanned, committed artifact and into an unbounded run log this
				// pipeline salvages — the exact exposure the scan exists to prevent.
				// It must not inherit an unqualified print pattern from here.
				t.Errorf("#1941: %s did not survive the round trip: wrote %v, read back %v; "+
					"this record is the capture's only durable trace",
					want[i].name, want[i].value, have[i].value)
			}
		}
	})

	// ONE ASSERTION, FOUR HAZARDS: a .tmp stranded beside the target by a copy
	// instead of a rename, any stray file, a write that escaped to the package's
	// real testdata/ (which leaves this tempdir at ZERO entries — the relative-path
	// hazard no AST ban can close), and a writer that minted its target name some
	// other way instead of calling askQuestionFixtureName from the record's own
	// claude_version_slug.
	//
	// That last covers a writer fed ClaudeVersionRaw instead of the slug — the raw
	// field is a whole `claude --version` line and slugs to something else entirely
	// — a different prefix or extension, and a writer that ignores dir. It does NOT
	// cover a writer that skipped versionSlug: see the 0-red limit on this test's
	// doc comment.
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("#1941: list the fixture directory for claude_version_slug %q: %v",
			rec.ClaudeVersionSlug, err)
	}
	names := make([]string, 0, len(entries))
	for _, e := range entries {
		names = append(names, e.Name())
	}
	wantName := askQuestionFixtureName(rec.ClaudeVersionSlug)
	if len(names) != 1 || names[0] != wantName {
		t.Errorf("#1941: the target directory holds %q, want exactly [%q]: a .tmp left here is a "+
			"half-written fixture a later commit would pick up, an empty directory means the "+
			"bytes went somewhere the caller never chose — a relative testdata/ included — and "+
			"a differently-spelled entry means the writer formats its own name, or mints it "+
			"from claude_version_raw, instead of calling askQuestionFixtureName on the record's "+
			"own claude_version_slug", names, wantName)
	}
}

// --- the planted refusal --------------------------------------------------------

// TestAskQuestionFixture_ScanRefusesAPlantedValue is #1941's AC 2 refusal half
// and AC 3: a record carrying a planted value of an armed class is refused, and
// the refusal is decided by — and reports — the scan's class names and count
// alone.
//
// IT EXERCISES THE SCAN OVER THE MARSHALLED RECORD, NEVER
// writeAskQuestionFixture's FATAL. A t.Fatalf from inside the writer takes the
// calling subtest down with it, there is no fake testing.TB in this package and
// testing.TB cannot be implemented outside testing, so nothing can assert on a
// refusal raised from inside one — t.Run's bool return cannot un-fail a subtest
// whose failure has already propagated to the parent. The assertion is on the
// DECIDING VALUE instead: scanAskQuestionFixture refuses iff len(hits) > 0. That
// same limit is why AC 3's "never prints the value" half is a property discharged
// by CONSTRUCTION at the scan step rather than a row here.
//
// WHAT THIS TEST DOES NOT PROVE, so that nobody credits it with more: it does not
// prove that scanAskQuestionFixture CALLS scan. That is construction — the step
// is the sole producer of the write's bytes and the scan is inside it — and it is
// the one untestable link in the chain. What it proves is that a fixed-class
// value planted in THIS record's marshalled form IS reported, by name, by the
// scanner both offline callers pass.
//
// It does NOT re-scan anything under testdata/, and the temptation is real
// because the fixed half of this net exists partly so offline validation can
// re-scan a committed capture forever. Twelve of the seventeen committed captures
// still carry a deny class as of 2026-09-01, so such a row would be red on
// arrival — and this file's finOfflineExecBans entry fences it off from that
// directory anyway. The scan this slice ships is on the WRITE PATH ONLY.
//
// The failure messages name class constants and the hits slice. They never print
// a plant, the blob, the record, the scanner or a needle. Every value here is
// synthetic, so printing one would leak nothing; the point is that #1938
// inherits no pattern worth copying.
func TestAskQuestionFixture_ScanRefusesAPlantedValue(t *testing.T) {
	t.Parallel()

	scanner := dropcapScanner{needles: dropcapFixedNeedles()}

	clean, err := json.MarshalIndent(askQuestionFullRecord(), "", "  ")
	if err != nil {
		t.Fatalf("#1941: marshal the unplanted fixture: %v", err)
	}
	cleanHits, notApplied := scanner.scan(clean)

	// The two vacuity controls, and they must Fatalf rather than skip: a property
	// that cannot discriminate is a broken instrument, not a passing test. Two
	// distinct failures, so two messages.
	//
	// The first is also the one row that says out loud WHY the round trip's
	// writeAskQuestionFixture call does not fatal: this fixture is deny-class free.
	if len(cleanHits) != 0 {
		t.Fatalf("#1941: the UNPLANTED fixture already hits %d class(es) %v, so the planted rows "+
			"below cannot tell \"the plant was seen\" from \"this record always hits\" — and the "+
			"round trip, which writes this same record, is now fataling inside the writer too",
			len(cleanHits), cleanHits)
	}
	// The five fixed needles are exempt from dropcapMinNeedle by construction. If a
	// later edit marked one dynamic, its class would be silently skipped, the
	// planted rows would go green-and-vacuous, and nothing else would notice.
	if len(notApplied) != 0 {
		t.Fatalf("#1941: the offline scanner reports %d class(es) NOT APPLIED %v; every fixed "+
			"needle is exempt from the dropcapMinNeedle minimum by construction, so a skipped "+
			"one means a fixed needle was marked dynamic and the rows below go "+
			"green-and-vacuous", len(notApplied), notApplied)
	}

	// An anonymous struct slice inside the test, which is what the sibling family's
	// sweep does. #1944 already declares askQuestionNameRow at PACKAGE scope in this
	// same package — its own doc comment claims otherwise — so a row type declared
	// here would be a second one competing for the same conceptual name.
	rows := []struct {
		name  string
		plant string
		class string
	}{
		{
			name:  "an sk-ant- credential prefix planted in tool_input",
			plant: askQuestionPlantedKeyPrefix,
			class: dropcapDenySkAnt,
		},
		{
			name:  "an operator path planted in tool_input",
			plant: askQuestionPlantedPath,
			class: dropcapDenyUsers,
		},
	}

	for _, row := range rows {
		t.Run(row.name, func(t *testing.T) {
			// Parallel, and safe: askQuestionFullRecord hands out a FRESH POINTER per
			// call, so a row's mutation cannot race a sibling's, and one dropcapScanner
			// value serves both — it is append-only during construction and read-only
			// afterwards, and scan is a value receiver that allocates its own results.
			t.Parallel()

			rec := askQuestionFullRecord()
			rec.ToolInput = askQuestionPlantedInput(row.plant)

			planted, err := json.MarshalIndent(rec, "", "  ")
			if err != nil {
				t.Fatalf("#1941: marshal the planted fixture: %v", err)
			}
			hits, _ := scanner.scan(planted)
			if !dropcapContains(hits, row.class) {
				t.Errorf("#1941: hits = %v, want %q among them: a value of that class planted in "+
					"tool_input survived the deny-scan, so writeAskQuestionFixture would commit "+
					"it and the fail-closed net this slice exists for is decorative",
					hits, row.class)
			}
		})
	}
}
