//go:build e2e_realclaude

package realclaude

// #1702 — the write half of the `initialize` control-request capture: the writer
// that puts #1701's record on disk under #1696's minted name, into a directory
// its caller chooses, and the offline round trip proving no field is dropped on
// the way.
//
// A measurement whose only trace is a test log evaporates when the run ends, so
// #1688's artifact is the point — and an artifact is worth committing only if it
// is COMPLETE (no field silently dropped on the way to disk), BOUNDED (no
// unbounded credential-bearing capture) and ATOMIC (no half-written residue
// stranded for a later commit). None of the three needs a claude binary. This
// file settles all three.
//
// # What this file deliberately is not
//
// It adds no field to initControlFixtureRecord and mints no second fixture —
// both are #1701's, and this file reads them.
//
// The scope limit that remains is the ROUND TRIP's, not the file's:
// initControlFullRecord's stderr_capture is well under stderrFixtureCap, so
// writeInitControlFixture's capFixtureCapture call is a no-op inside
// TestInitControlFixture_RoundTripsEveryFieldIntoOneNamedEntry and that row
// compares equal on both sides. TestInitControlFixture_WriterCapsStderrCapture
// mutates the record to an over-cap capture and is what proves BOUNDED. The
// writer's no-mutation contract is structurally the same claim — observing it
// needs a capture the cap actually shortens — so it rides there too, exactly as
// TestPoolRevokeFixture_WriterCapsChildOutputCapture carries the sibling's rather
// than its round trip. No live run: that is #1688.
//
// # What the round trip catches, and what it cannot
//
// The read-back decodes through the struct that wrote the file, so it is
// symmetric and CANNOT catch a misspelled JSON tag. #1662's code review sharpened
// that limit: even a UNIQUE wrong tag round-trips green, because only a COLLIDING
// tag makes encoding/json drop both. Applying initControlFixtureFields to both
// sides does not change it — the listing labels failure messages here rather than
// checking anything.
//
// The limit is stated, not claimed away, and it must NOT be dismissed the way
// #1662's header dismisses its own. #1662's key names are read by humans alone.
// THESE ARE NOT: #1690's decoder and #1692's fake read this contract, so a
// misspelled tag here is a real defect two tickets downstream — one this test is
// simply not the instrument for. The instrument is a reviewer diffing #1701's
// hand-written initControlFixtureFields against the struct's tags, which is why
// that listing must never be regenerated by reflection.
//
// What the round trip does catch is a field dropped or tagged `json:"-"`, a
// COLLIDING pair of tags, a writer that formats its own filename instead of
// minting one, a writer that ignores its dir parameter, and a rename that never
// happened.
//
// # Offline, and the one ban this file must not copy from its siblings
//
// This file reaches no live claude, no daemon, no subprocess and no credential:
// it must not reach resolveClaudeBin, probeClaudeVersion, WithWorktree,
// WithWorktreeAuthenticated or captureClaudeVersion, nor os.Getenv, os.Environ or
// os.LookupEnv, nor packageDir or any of the wrappers setModeFixturePath,
// writeSetModeFixture and writeFixture that resolve the committed testdata/
// through it.
//
// It DOES write, read back and list a directory — that is its entire subject — so
// unlike initialize_control_names_test.go and initialize_control_record_test.go
// it bans none of the os read/write helpers. The relative-path hazard those bans
// close for the two files that perform no I/O — `go test` runs in the package
// source directory, so a RELATIVE os.WriteFile("testdata/…") reaches the
// committed fixtures without naming packageDir at all — is closed here instead by
// the exactly-one-entry assertion below: bytes that escaped to a relative
// testdata/ leave the t.TempDir() holding ZERO entries.
//
// TestFinOfflineFilesReachNoExecHelper enforces the ban over this file's AST
// rather than over this paragraph — it parses without parser.ParseComments
// precisely so the check cannot answer itself out of the sentence that states it.
//
//	go test -tags e2e_realclaude -race -count=1 -v \
//	  -run 'TestInitControlFixture_|TestFinOfflineFilesReachNoExecHelper' \
//	  ./internal/e2e/realclaude/
//
// Both must report PASS — not SKIP, not "no tests to run" — on a machine with no
// claude and no credentials. Read the count of tests that executed, never the
// exit code: this package is behind the e2e_realclaude tag, `make check` never
// compiles it, and the suite exits 0 both on a build failure and on a full
// credentials skip.

import (
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"
	"unicode/utf8"
)

// --- the writer -----------------------------------------------------------------

// writeInitControlFixture writes rec into dir and returns the written path.
//
// dir is a PARAMETER, deliberately — unlike writeSetModeFixture, which hardcodes
// packageDir(t)/testdata and is correct for #1595's live run. That is what lets
// this writer settle here against a t.TempDir(), with #1688 passing the real
// testdata/ later. os.MkdirAll is a no-op against a t.TempDir() and is kept for
// the same reason the sibling writer keeps it: #1688's directory may not exist.
//
// The filename is MINTED by initControlFixtureName from ClaudeVersion passed
// through UNMODIFIED, never formatted here. A writer that interpolates its own
// "initialize_control_v%s.json" puts #1688's committed artifact back inside the
// overwrite hazard #1696's lock exists to close, with #1696's own test still
// green. The input is claude_version and not claude_version_raw: #1701's
// distinctness property keeps the two strings apart, and the raw form carries a
// space and parens that slug to something else entirely.
//
// rec is never mutated — the cap lands on a local copy. THE SHALLOW COPY IS
// SUFFICIENT ONLY BECAUSE THE SOLE MUTATION IS TO A string FIELD: `out := *rec`
// shares every slice header with the caller's record, so a future writer that
// capped one of the slice-valued fields would be writing through the caller's
// backing array from behind a copy that looks defensive. Nothing here proves the
// cap bound or the no-mutation contract; both are
// TestInitControlFixture_WriterCapsStderrCapture's.
//
// Failure is always t.Fatalf naming claude_version and the error and NOTHING
// ELSE: a %+v of the record would move up to stderrFixtureCap bytes of child
// output out of the bounded file and into an unbounded run log, the exact thing
// the cap exists to prevent. claude_version is safe to print — it is already in
// the filename.
func writeInitControlFixture(t *testing.T, dir string, rec *initControlFixtureRecord) string {
	t.Helper()

	out := *rec
	out.StderrCapture = capFixtureCapture(out.StderrCapture)

	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("#1702: mkdir fixture dir for claude_version %q: %v", out.ClaudeVersion, err)
	}
	path := filepath.Join(dir, initControlFixtureName(out.ClaudeVersion))
	data, err := json.MarshalIndent(&out, "", "  ")
	if err != nil {
		t.Fatalf("#1702: marshal fixture for claude_version %q: %v", out.ClaudeVersion, err)
	}
	// Temp file and rename, the discipline both sibling writers use: an
	// interrupted run must not strand a half-written fixture under the target
	// name for a later commit.
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o644); err != nil {
		t.Fatalf("#1702: write fixture tmp for claude_version %q: %v", out.ClaudeVersion, err)
	}
	if err := os.Rename(tmp, path); err != nil {
		t.Fatalf("#1702: rename fixture for claude_version %q: %v", out.ClaudeVersion, err)
	}
	return path
}

// --- the raw-JSON normaliser --------------------------------------------------

// compactInitControlRawRows returns rows with every raw-JSON-bearing row
// normalised through compactRawMessages, plus the names of the rows it touched.
//
// json.MarshalIndent indents INSIDE an embedded raw message, so an envelope
// written and read back is not byte-equal and a PERFECTLY CORRECT writer reddens.
// #1662 hit this with one such field; this record has THREE, of two different Go
// types — control_request_sent is a json.RawMessage, control_responses and
// stdout_events are []json.RawMessage. Measured on this toolchain 2026-08-22,
// byte-equality after the round trip is false for all three shapes and compaction
// restores it for all three; a plain string field is unaffected. Normalising only
// control_responses — #1662's shape — is red on arrival here, not a latent risk.
//
// SELECTION IS BY THE ROW'S GO TYPE, NOT BY THE THREE NAMES. #1701's length
// assertion guarantees a fourth raw-JSON field added later arrives with a listing
// row, and a name-scoped normaliser would then redden against an honest writer.
// The type switch covers it automatically. The three names are still the
// checkable list, which is what the touched-name return is for: the round trip
// asserts the touched set is exactly those three, so a normaliser widened to
// blind rows it should not is caught, and one that silently stopped matching
// reports as one clear failure instead of three confusing row mismatches.
//
// compactRawMessages takes []json.RawMessage, so the single-valued field is
// wrapped and unwrapped HERE rather than growing a second helper. Unwrapping
// keeps the row's dynamic type identical to the record's, so a failure message
// reads as that field's own shape.
//
// ONE DIAGNOSIS TRAP, expected rather than broken. A dropped or `json:"-"`-tagged
// control_request_sent leaves the read-back side nil, and json.Compact over nil
// returns "unexpected end of JSON input" — so that mutant surfaces as
// compactRawMessages' own t.Fatalf, which carries #1662's ticket number and names
// control_responses explicitly. The verdict is correct and the mutant IS red; the
// diagnosis points at the wrong file and the wrong field. The two slice-valued
// fields degrade cleanly to an empty slice and report as ordinary row mismatches.
func compactInitControlRawRows(t *testing.T, rows []initControlFixtureField) ([]initControlFixtureField, []string) {
	t.Helper()

	out := make([]initControlFixtureField, 0, len(rows))
	touched := make([]string, 0, len(rows))
	for _, row := range rows {
		switch v := row.value.(type) {
		case json.RawMessage:
			row.value = compactRawMessages(t, []json.RawMessage{v})[0]
			touched = append(touched, row.name)
		case []json.RawMessage:
			row.value = compactRawMessages(t, v)
			touched = append(touched, row.name)
		}
		out = append(out, row)
	}
	return out, touched
}

// --- the round trip -------------------------------------------------------------

// TestInitControlFixture_RoundTripsEveryFieldIntoOneNamedEntry is #1702's AC 2 and
// AC 3: every field of #1701's fully-populated record survives
// write-then-read-back, and the target directory afterwards holds exactly one
// entry, named exactly what initControlFixtureName mints.
//
// The subtests share one written artifact and are deliberately NOT parallel; the
// parent owns the tempdir.
//
// It does not restate #1701's properties. Non-zero and same-typed distinctness
// ship in TestInitControlFullRecord_PinsEveryFieldAndTheSluggableVersionToken and
// are preconditions this test consumes rather than assertions it repeats — and
// there is no cap row, because the fixture's capture is far under the cap and
// that row is TestInitControlFixture_WriterCapsStderrCapture's whole subject.
func TestInitControlFixture_RoundTripsEveryFieldIntoOneNamedEntry(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	rec := initControlFullRecord()
	path := writeInitControlFixture(t, dir, rec)

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("#1702: read back the fixture for claude_version %q: %v", rec.ClaudeVersion, err)
	}
	var got initControlFixtureRecord
	if err := json.Unmarshal(data, &got); err != nil {
		t.Fatalf("#1702: decode the fixture for claude_version %q: %v", rec.ClaudeVersion, err)
	}

	// Both sides go through the SAME listing, applied to the written record and
	// to its decode. There is deliberately no length guard before the zip: both
	// slices come from one function over one struct type, so a divergence is
	// impossible and the guard could never redden.
	want, touched := compactInitControlRawRows(t, initControlFixtureFields(rec))
	have, _ := compactInitControlRawRows(t, initControlFixtureFields(&got))

	t.Run("every field survives the round trip", func(t *testing.T) {
		for i := range want {
			if !reflect.DeepEqual(want[i].value, have[i].value) {
				// Printing both values is safe HERE AND ONLY HERE: every value in
				// this record is a #1701 synthetic literal, and the diagnostic is
				// worth far more than protecting a 53-byte fixture string. #1688
				// fills this same record from a live child and must not inherit
				// the pattern — its stderr_capture is real, bounded child output,
				// and TestInitControlFixture_WriterCapsStderrCapture's rows report
				// lengths and a short prefix for exactly that reason.
				t.Errorf("#1702: %s did not survive the round trip: wrote %v, read back %v; "+
					"#1688 commits this record as its only durable trace",
					want[i].name, want[i].value, have[i].value)
			}
		}
	})

	t.Run("the normaliser touches exactly the three raw-JSON rows", func(t *testing.T) {
		// The type-scoped selection above is what keeps a fourth raw-JSON field
		// covered automatically; this is what keeps that scoping honest. Sorted
		// because the claim is about the SET of rows, not the listing's order.
		wantTouched := []string{"control_request_sent", "control_responses", "stdout_events"}
		gotTouched := append([]string(nil), touched...)
		sort.Strings(gotTouched)

		if !reflect.DeepEqual(gotTouched, wantTouched) {
			t.Errorf("#1702: the normaliser touched %v, want exactly %v: widened, it blinds more "+
				"than the whitespace json.MarshalIndent introduces and a genuinely altered row "+
				"reads back equal; narrowed, it reddens against an honest writer because an "+
				"embedded raw message is never byte-equal after a round trip",
				gotTouched, wantTouched)
		}
	})

	// One assertion, four hazards: a .tmp stranded beside the target by a copy
	// instead of a rename, any stray file, a write that escaped to the package's
	// real testdata/ (which leaves this tempdir at ZERO entries — the
	// relative-path hazard no AST ban can close), and a writer that minted its
	// target name some other way instead of calling initControlFixtureName. The
	// last is non-vacuous only because #1701's claude_version carries an uppercase
	// run versionSlug rewrites; against a slug-clean token it would be 0-red.
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("#1702: list the fixture directory for claude_version %q: %v", rec.ClaudeVersion, err)
	}
	names := make([]string, 0, len(entries))
	for _, e := range entries {
		names = append(names, e.Name())
	}
	wantName := initControlFixtureName(rec.ClaudeVersion)
	if len(names) != 1 || names[0] != wantName {
		t.Errorf("#1702: the target directory holds %q, want exactly [%q]: a .tmp left here is a "+
			"half-written fixture a later commit would pick up, an empty directory means the "+
			"bytes went somewhere the caller never chose, and a differently-spelled entry means "+
			"the writer formats its own name instead of minting through initControlFixtureName",
			names, wantName)
	}
}

// --- the cap ------------------------------------------------------------------------

// TestInitControlFixture_WriterCapsStderrCapture is #1700: writeInitControlFixture
// bounds the free-text capture, so #1688 cannot forget to. stderr_capture absorbs
// unbounded text from a process this repo does not control, and the file it lands
// in gets committed.
//
// capFixtureCapture is already proven by #1662's own cap test. What is proven here
// is different and unreachable by calling that helper: that THIS writer calls it,
// on THE RIGHT FIELD, and that the bound survives a write and a read-back FROM
// DISK. Every assertion therefore runs over the bytes read out of the written file
// — a direct call to capFixtureCapture inside an assertion collapses the
// cap-omitted and wrong-field mis-implementations to green, because it cannot
// catch a writer that never applied the cap at all. Every length assertion is on
// len(), never on rune count: the cap is a byte cap and truncateString slices
// bytes.
//
// # Why two rows, and why neither is dead weight
//
// Each row is the sole red for a distinct mis-implementation, measured through
// json.MarshalIndent and back:
//
//   - Calling truncateString(s, stderrFixtureCap) directly instead of
//     capFixtureCapture: the multi-byte row reads back at 8194, over the bound the
//     writer states, and is RED — SOLE. encoding/json does not error on invalid
//     UTF-8, it substitutes U+FFFD at three bytes per invalid byte, so a byte cap
//     with no rune-boundary trim reads back OVER its own cap. The ASCII row, where
//     a byte cut is a rune cut, stays perfectly green.
//   - A trim that removes one byte too many: the ASCII row reads back at 8191 and
//     is RED — SOLE. That is why the ASCII assertion must be EXACT while the
//     multi-byte one can only be a RANGE — the rune-boundary trim legitimately
//     removes up to utf8.UTFMax-1 bytes, so a range is the strongest claim the
//     multi-byte row can make and an over-trim hides inside it.
//   - A writer that caps the caller's record instead of a copy: only the
//     no-mutation check is RED — SOLE.
//
// There is deliberately no under-cap row. Both capFixtureCapture and
// truncateString carry a len(s) <= max early return, so an under-cap input reddens
// nothing; #1662's header records that as measured. Two cases, not three.
//
// # Do not print the capture
//
// Failure messages report LENGTHS, the cap constant, the row's diagnosis and at
// most a 16-byte prefix. A %q of want/got here dumps up to stderrFixtureCap bytes
// of child output into an unbounded -v run log, which defeats the field's entire
// purpose. The 16-byte prefix is safe only because this test's literals are
// synthetic; #1688 must not inherit even that much.
func TestInitControlFixture_WriterCapsStderrCapture(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		capture string
		// precheck asserts a property of this row's OWN literal that the row's
		// ability to discriminate depends on. nil where the row has none.
		//
		// This is a deliberate divergence from
		// TestPoolRevokeFixture_WriterCapsChildOutputCapture, which guards the
		// same property with an `if tc.name == …` branch in the loop body. A
		// name-string match stops firing silently if anyone renames the row,
		// which is exactly the class of silent degradation the control exists to
		// prevent.
		precheck func(t *testing.T, capture string)
		check    func(t *testing.T, capture, back string)
	}{
		{
			name:    "over_cap_ascii",
			capture: strings.Repeat("A", stderrFixtureCap+1024),
			check: func(t *testing.T, capture, back string) {
				// EXACT, not a range: this is the sole red for a trim that removes
				// one byte too many, and a range here would swallow it.
				if len(back) != stderrFixtureCap {
					t.Errorf("#1700: a %d-byte capture reads back at %d bytes, want exactly %d; "+
						"the writer leaves the cap to its caller, or trims past the boundary, "+
						"and #1688 then commits an unbounded credential-bearing dump",
						len(capture), len(back), stderrFixtureCap)
				}
			},
		},
		{
			// One ASCII byte then two-byte runes, so rune starts land on odd byte
			// indices and the byte at stderrFixtureCap is a CONTINUATION byte —
			// truncateString alone would split a rune here.
			name:    "over_cap_multibyte",
			capture: "A" + strings.Repeat("é", 5000),
			precheck: func(t *testing.T, capture string) {
				// The vacuity control, and it must Fatalf rather than skip: if a
				// later edit to the literal moves the boundary onto a rune start,
				// truncateString alone no longer splits a rune, the
				// direct-truncateString mis-implementation goes green, and this
				// row proves nothing while still passing. A row that cannot
				// discriminate is a broken instrument, not a passing test.
				if utf8.RuneStart(capture[stderrFixtureCap]) {
					t.Fatalf("#1700: byte %d of this row's %d-byte capture starts a rune, so "+
						"truncateString alone would not split one and the rune-boundary trim "+
						"is never exercised", stderrFixtureCap, len(capture))
				}
			},
			check: func(t *testing.T, capture, back string) {
				// A RESTATEMENT, not coverage for any mis-implementation. Measured:
				// the read-back is valid UTF-8 under every one of them, because
				// that same U+FFFD substitution happens on the way to disk — a
				// split rune surfaces as a length and prefix violation, never as an
				// invalid one. It is carried because it names the failure mode the
				// range check below actually detects.
				if !utf8.ValidString(back) {
					t.Errorf("#1700: the %d-byte read-back is not valid UTF-8; the writer split a "+
						"rune", len(back))
				}
				if len(back) > stderrFixtureCap || len(back) < stderrFixtureCap-(utf8.UTFMax-1) {
					t.Errorf("#1700: a %d-byte multi-byte capture reads back at %d bytes, want "+
						"within [%d, %d]; encoding/json substitutes U+FFFD per invalid byte, so a "+
						"byte cap with no rune-boundary trim reads back OVER the cap it states",
						len(capture), len(back), stderrFixtureCap-(utf8.UTFMax-1), stderrFixtureCap)
				}
				if !strings.HasPrefix(capture, back) {
					t.Errorf("#1700: the %d-byte read-back (first bytes %q) is not a prefix of the "+
						"original; the writer rewrote content rather than trimming a split tail, "+
						"and a substituted U+FFFD is not in the original either",
						len(back), back[:min(16, len(back))])
				}
			},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			if tc.precheck != nil {
				tc.precheck(t, tc.capture)
			}

			// INSIDE the subtest. The fresh pointer per call is why
			// initControlFullRecord is a function and not a package-level var:
			// hoisting this to the parent makes the assignment below a -race data
			// race across two parallel subtests, which its doc comment predicts.
			rec := initControlFullRecord()
			rec.StderrCapture = tc.capture
			// A fresh tempdir per row, and not stylistic: both rows mint the SAME
			// filename from the same ClaudeVersion, so a shared directory would
			// have them overwrite each other's artifact under a racing read-back.
			path := writeInitControlFixture(t, t.TempDir(), rec)

			// The no-mutation contract, checked BEFORE the read-back: the writer
			// caps a copy, so the caller's record still holds everything it held.
			//
			// Scoped to the capped field deliberately. writeInitControlFixture's
			// `out := *rec` is a shallow copy sharing every slice header with the
			// caller, sufficient today only because the sole mutation is to a
			// string field. No mis-implementation above violates the slice-valued
			// fields; the shallow-copy hazard is a note for whoever caps a slice
			// field later, not something to widen this check for.
			if len(rec.StderrCapture) != len(tc.capture) {
				t.Errorf("#1700: the writer left the caller's record at %d bytes, want the "+
					"original %d; it caps in place, so an assertion against the caller's record "+
					"compares a mutated value with its own decode and proves nothing",
					len(rec.StderrCapture), len(tc.capture))
			}

			data, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("#1700: read back the capped fixture for claude_version %q: %v",
					rec.ClaudeVersion, err)
			}
			var back initControlFixtureRecord
			if err := json.Unmarshal(data, &back); err != nil {
				t.Fatalf("#1700: decode the capped fixture for claude_version %q: %v",
					rec.ClaudeVersion, err)
			}
			tc.check(t, tc.capture, back.StderrCapture)
		})
	}
}
