//go:build e2e_realclaude

package realclaude

// #1702 — the write half of the `initialize` control-request capture: the writer
// that puts #1701's record on disk under a minted name, into a directory its
// caller chooses, and the offline round trip proving no field is dropped on the
// way. The name came from #1696's one-input namer until #1722 migrated the writer
// onto #1712's arm-carrying one.
//
// A measurement whose only trace is a test log evaporates when the run ends, so
// #1688's artifact is the point — and an artifact is worth committing only if it
// is COMPLETE (no field silently dropped on the way to disk), BOUNDED (no
// unbounded credential-bearing capture) and ATOMIC (no half-written residue
// stranded for a later commit). None of the three needs a claude binary. This
// file settles all three.
//
// #1748 added a FOURTH, and it is the only one that can refuse the write:
// SCAN-CLEAN — the marshalled bytes carry no value of an armed deny class. That
// property lives in scanInitControlFixture, ahead of every filesystem call, and it
// needs no claude binary either.
//
// # What this file deliberately is not
//
// It adds no field to initControlFixtureRecord and mints no second fixture —
// both are #1701's, and this file reads them.
//
// The scope limit that remains is the ROUND TRIP's, not the file's:
// initControlFullRecord's stderr_capture is well under stderrFixtureCap, so
// scanInitControlFixture's capFixtureCapture call is a no-op inside
// TestInitControlFixture_RoundTripsEveryFieldIntoOneNamedEntry and that row
// compares equal on both sides. TestInitControlFixture_WriterCapsStderrCapture
// mutates the record to an over-cap capture and is what proves BOUNDED. The
// writer's no-mutation contract is structurally the same claim — observing it
// needs a capture the cap actually shortens — so it rides there too, exactly as
// TestPoolRevokeFixture_WriterCapsChildOutputCapture carries the sibling's rather
// than its round trip. No live run: that is #1688.
//
// #1722 added a third test here for the same structural reason the cap has its
// own: TestInitControlFixture_RoundTripsAnUnansweredWaitBesideCapturedBytes needs
// a record the fully-populated fixture cannot be — captured response bytes beside
// an UNSATISFIED wait — and #1701's non-zero property forbids that pair there,
// since a bool is non-zero only when true. It lands in this file rather than the
// record's because it writes and reads back, and this is the file whose
// finOfflineExecBans entry permits os.WriteFile and os.ReadFile.
//
// # What the round trip catches, and what it cannot
//
// The read-back decodes through the struct that wrote the file, so it is
// symmetric and CANNOT catch a misspelled JSON tag. #1662's code review sharpened
// that limit: even a UNIQUE wrong tag round-trips green, because only a COLLIDING
// tag makes encoding/json drop both. Applying initControlFixtureFields to both
// sides does not change it — the listing labels failure messages here rather than
// checking anything.
//
// The limit is stated, not claimed away, and it must NOT be dismissed the way
// #1662's header dismisses its own. #1662's key names are read by humans alone.
// THESE ARE NOT: #1690's decoder and #1692's fake read this contract, so a
// misspelled tag here is a real defect two tickets downstream — one this test is
// simply not the instrument for. The instrument is a reviewer diffing #1701's
// hand-written initControlFixtureFields against the struct's tags, which is why
// that listing must never be regenerated by reflection.
//
// What the round trip does catch is a field dropped or tagged `json:"-"`, a
// COLLIDING pair of tags, a writer that formats its own filename instead of
// minting one, a writer that ignores its dir parameter, and a rename that never
// happened.
//
// # Offline, and the one ban this file must not copy from its siblings
//
// This file reaches no live claude, no daemon, no subprocess and no credential:
// it must not reach resolveClaudeBin, probeClaudeVersion, WithWorktree,
// WithWorktreeAuthenticated or captureClaudeVersion, nor os.Getenv, os.Environ or
// os.LookupEnv, nor packageDir or any of the wrappers setModeFixturePath,
// writeSetModeFixture and writeFixture that resolve the committed testdata/
// through it.
//
// It DOES write, read back and list a directory — that is its entire subject — so
// unlike initialize_control_names_test.go and initialize_control_record_test.go
// it bans none of the os read/write helpers. The relative-path hazard those bans
// close for the two files that perform no I/O — `go test` runs in the package
// source directory, so a RELATIVE os.WriteFile("testdata/…") reaches the
// committed fixtures without naming packageDir at all — is closed here instead by
// the exactly-one-entry assertion below: bytes that escaped to a relative
// testdata/ leave the t.TempDir() holding ZERO entries.
//
// TestFinOfflineFilesReachNoExecHelper enforces the ban over this file's AST
// rather than over this paragraph — it parses without parser.ParseComments
// precisely so the check cannot answer itself out of the sentence that states it.
//
//	go test -tags e2e_realclaude -race -count=1 -v \
//	  -run 'TestInitControlFixture_|TestFinOfflineFilesReachNoExecHelper' \
//	  ./internal/e2e/realclaude/
//
// Both must report PASS — not SKIP, not "no tests to run" — on a machine with no
// claude and no credentials. Read the count of tests that executed, never the
// exit code: this package is behind the e2e_realclaude tag, `make check` never
// compiles it, and the suite exits 0 both on a build failure and on a full
// credentials skip.

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"
	"unicode/utf8"
)

// --- the fail-closed scan -----------------------------------------------------

// scanInitControlFixture returns the exact bytes writeInitControlFixture will put
// on disk, refusing the record outright when the deny-scan hits.
//
// #1748. Every byte this family COMMITS is claude's stdout, and until this step
// no deterministic check ran over any of it — #1688's clean bill came from two
// human reads of the committed JSON, and both passed an `account` and a `pid`
// under response.response. #1732 and #1733 landed the redaction table; a table
// only rewrites what it PREDICTED. This is the fail-closed net behind it,
// deliberately different fabric: it rewrites nothing and refuses the write.
//
// IT MAKES NO FILESYSTEM CALL OF ANY KIND, and that is the mechanism rather than
// a coincidence of layout. This step is the sole producer of the bytes the writer
// puts on disk and the scan is INSIDE it, so the writer cannot hold a blob the
// scan has not passed; and the first filesystem call anywhere on the path is the
// writer's os.MkdirAll, strictly after this returns. A hit therefore leaves the
// target directory holding nothing — no record, no .tmp under any name, nothing
// written and then deleted. That claim has no seam to observe it from (a hit is a
// t.Fatalf that takes the calling subtest down), so it is discharged by
// construction; the executable half of it is
// TestInitControlFixture_WriterCapsStderrCapture's byte-identity row, which reads
// the same mechanism from the other end.
//
// THE CAP LIVES HERE, NOT IN THE WRITER AND NOT IN THE CALLER. The bytes scanned
// are then exactly the bytes on disk, so a needle surviving only in the truncated
// tail is correctly not reported — the file cannot carry what the scan did not
// see, and the scan does not refuse over bytes the file will not carry. Capping in
// the CALLER mutates the caller's record, which the cap test's no-mutation check
// already reddens. Capping in the WRITER, between this scan and the write, leaves
// the scanned bytes longer than the disk bytes — and the byte-identity row is that
// mutant's SOLE red, because every length, prefix and UTF-8 assertion in the cap
// test stays green over a file that is still correctly bounded.
//
// THE STEP MUST NEVER MODIFY A FIELD initControlArmFixtureName READS. The writer
// mints the name from the CALLER's record while writing the bytes this copy
// produced, which is sound only while the two agree on claude_version and arm. The
// cap is scoped to stderr_capture, so they do — and that equivalence is not left as
// a claim: TestInitControlFixture_RoundTripsEveryFieldIntoOneNamedEntry computes
// its expected name from the caller's record, so a step that touched either field
// reddens there.
//
// rec is never mutated — the cap lands on a local copy. THE SHALLOW COPY IS
// SUFFICIENT ONLY BECAUSE THE SOLE MUTATION IS TO A string FIELD: `out := *rec`
// shares every slice header with the caller's record, so a future step that capped
// one of the slice-valued fields would be writing through the caller's backing
// array from behind a copy that looks defensive. Nothing here proves the cap bound
// or the no-mutation contract; both are
// TestInitControlFixture_WriterCapsStderrCapture's.
//
// # What it does NOT do that dropcapWriteRecord does
//
// The exemplar additionally scans every base64 payload's decoded bytes, because
// bytes.Contains cannot see through base64. initControlFixtureRecord carries NO
// base64-encoded field — its payload-bearing fields are json.RawMessage and plain
// strings, all of which the blob scan reads directly. dropcapBase64Payloads and
// dropcapLocateHits are deliberately not ported; there is nothing here for either
// to narrow, and an offset would localise the hit INSIDE the record, which is that
// helper's job in the sibling and deliberately nobody's here.
//
// scan's second return is discarded. The arming census is already a recorded record
// field — credential_scan_applied, filled at the construction site by
// initControlScanApplied — so reporting it again from here would duplicate the fact
// in a second place that can drift from the first.
//
// # The refusal, and the two rules that bind every line added here
//
// On a hit: t.Fatalf naming the COUNT and the CLASS NAMES and nothing else. No
// excerpt, no record dump, no needle value, no byte offset. "Let me include the
// payload to help debug it" is exactly how a token reaches a salvaged run log and
// inverts the whole control. There is no fake testing.TB in this package and
// testing.TB cannot be implemented outside testing, so no row observes what this
// prints; the rule is the guard.
//
// NEVER FORMAT THE SCANNER. newDropcapScanner stores CLAUDE_CODE_OAUTH_TOKEN and
// ANTHROPIC_API_KEY as needle values, so a dropcapScanner in scope is TWO LIVE
// CREDENTIALS IN A STRUCT — no %v, %+v, %#v or %q on the scanner, on a needle or
// on the needle slice, here or in the writer or in any new row. initControlScrubbed
// does not catch it: that guard reads the CHILD's stderr, and this would be the
// harness's own output. runInitControlChild's doc states the same rule for the
// construction site.
//
// t.Fatalf requires the test goroutine. This step and the writer are both called
// directly from one — runInitControlChild's stdout reader goroutine calls neither —
// so t.Helper() plus a direct call is the whole discipline. Do not call either from
// a goroutine.
func scanInitControlFixture(t *testing.T, scanner dropcapScanner, rec *initControlFixtureRecord) []byte {
	t.Helper()

	out := *rec
	out.StderrCapture = capFixtureCapture(out.StderrCapture)

	data, err := json.MarshalIndent(&out, "", "  ")
	if err != nil {
		t.Fatalf("#1702: marshal fixture for claude_version %q arm %q: %v",
			rec.ClaudeVersion, rec.Arm, err)
	}
	hits, _ := scanner.scan(data)
	if len(hits) > 0 {
		t.Fatalf("#1748: deny-scan found %d denied class(es) in the fixture for claude_version %q "+
			"arm %q: %v\nNOTHING was written — no record, no .tmp, nothing under the target "+
			"directory at all. Extend newInitControlRedactor's table with the named class and "+
			"re-run one live capture. The offending value is deliberately not printed, and neither "+
			"is its offset: putting either in a run log this pipeline salvages is exactly the "+
			"exposure this scan exists to prevent",
			len(hits), rec.ClaudeVersion, rec.Arm, hits)
	}
	return data
}

// --- the writer -----------------------------------------------------------------

// writeInitControlFixture writes rec into dir and returns the written path.
//
// dir is a PARAMETER, deliberately — unlike writeSetModeFixture, which hardcodes
// packageDir(t)/testdata and is correct for #1595's live run. That is what lets
// this writer settle here against a t.TempDir(), with #1688 passing the real
// testdata/ later. os.MkdirAll is a no-op against a t.TempDir() and is kept for
// the same reason the sibling writer keeps it: #1688's directory may not exist.
//
// The bytes come from scanInitControlFixture and are written BYTE FOR BYTE, with
// nothing appended — not even dropcapWriteRecord's trailing newline, which would
// break the byte-identity contract by one byte. That step copies, caps, marshals
// and runs the deny-scan, and it touches the filesystem not at all, so the first
// filesystem call on this path is the os.MkdirAll below and a refused record
// strands nothing under dir. Read its doc for why the cap lives there.
//
// The filename is MINTED by initControlArmFixtureName from ClaudeVersion and Arm,
// BOTH passed through UNMODIFIED — from the CALLER's rec, not from the step's
// capped copy, which no longer exists out here. The two agree because the cap is
// scoped to stderr_capture; the step's doc carries that rule and names the row
// that enforces it. Never formatted here and never slugged here —
// that namer owns both columns. A writer that interpolates its own
// "initialize_control_v%s_%s.json" puts #1688's committed artifact back inside the
// overwrite hazard #1696's lock exists to close, with #1696's own test still
// green; one that interpolates the ARM raw reopens the traversal hazard
// setModeFixtureName still carries, which is the wrong pattern sitting in this
// same package waiting to be copied.
//
// #1722 migrated this off the one-input initControlFixtureName. Through that namer
// all three of #1715's arms mint one path: the last arm wins and the other two
// vanish with nothing red anywhere. The input is claude_version and not
// claude_version_raw: #1701's distinctness property keeps the two strings apart,
// and the raw form carries a space and parens that slug to something else
// entirely.
//
// DO NOT ADD A MEMBERSHIP OR SHAPE GUARD ON Arm HERE. Rejecting an arm outside
// initControlArms rejects initControlFullRecord's own synthetic arm — which is
// deliberately not a declared one, so that #1701's slug subtest has something to
// pin — and fatals the round trip below. The containment guarantee is lexical and
// belongs to the namer.
//
// rec is never mutated: the copy and the cap moved into scanInitControlFixture
// with #1748, and its doc carries the shallow-copy caveat that used to live here.
// Nothing here proves the cap bound or the no-mutation contract; both are
// TestInitControlFixture_WriterCapsStderrCapture's.
//
// The scanner is a PARAMETER, the way dir already is, and NEVER a newDropcapScanner
// call in this file. That constructor reads os.Getenv twice and realHome, and this
// file's finOfflineExecBans entry bans all four names precisely because the check is
// an AST identifier match — calling the constructor here would satisfy the ban on
// os.Getenv to the letter while destroying the offline property it protects. The
// five offline callers below pass dropcapScanner{needles: dropcapFixedNeedles()},
// which reads no environment and whose five needles are not dynamic, so
// dropcapMinNeedle never skips them and the net is armed identically on every
// machine. NEVER FORMAT THE SCANNER: see scanInitControlFixture's doc.
//
// Failure is always t.Fatalf naming claude_version and arm and the error and
// NOTHING ELSE: a %+v of the record would move up to stderrFixtureCap bytes of
// child output out of the bounded file and into an unbounded run log, the exact
// thing the cap exists to prevent. Both are safe to print for the same reason —
// each is already in the filename and neither came from the child. The arm joined
// the message with #1722's per-arm path: once #1715 writes three fixtures, a
// failure that cannot say which arm failed is a real diagnosis gap.
func writeInitControlFixture(t *testing.T, dir string, scanner dropcapScanner, rec *initControlFixtureRecord) string {
	t.Helper()

	// FIRST, and before any filesystem call: a refused record must strand nothing
	// under dir, not even a .tmp.
	data := scanInitControlFixture(t, scanner, rec)

	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("#1702: mkdir fixture dir for claude_version %q arm %q: %v",
			rec.ClaudeVersion, rec.Arm, err)
	}
	path := filepath.Join(dir, initControlArmFixtureName(rec.ClaudeVersion, rec.Arm))
	// Temp file and rename, the discipline both sibling writers use: an
	// interrupted run must not strand a half-written fixture under the target
	// name for a later commit.
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o644); err != nil {
		t.Fatalf("#1702: write fixture tmp for claude_version %q arm %q: %v",
			rec.ClaudeVersion, rec.Arm, err)
	}
	if err := os.Rename(tmp, path); err != nil {
		t.Fatalf("#1702: rename fixture for claude_version %q arm %q: %v",
			rec.ClaudeVersion, rec.Arm, err)
	}
	return path
}

// --- the raw-JSON normaliser --------------------------------------------------

// compactInitControlRawRows returns rows with every raw-JSON-bearing row
// normalised through compactRawMessages, plus the names of the rows it touched.
//
// json.MarshalIndent indents INSIDE an embedded raw message, so an envelope
// written and read back is not byte-equal and a PERFECTLY CORRECT writer reddens.
// #1662 hit this with one such field; this record has THREE, of two different Go
// types — control_request_sent is a json.RawMessage, control_responses and
// stdout_events are []json.RawMessage. Measured on this toolchain 2026-08-22,
// byte-equality after the round trip is false for all three shapes and compaction
// restores it for all three; a plain string field is unaffected. Normalising only
// control_responses — #1662's shape — is red on arrival here, not a latent risk.
//
// SELECTION IS BY THE ROW'S GO TYPE, NOT BY THE THREE NAMES. #1701's length
// assertion guarantees a fourth raw-JSON field added later arrives with a listing
// row, and a name-scoped normaliser would then redden against an honest writer.
// The type switch covers it automatically. The three names are still the
// checkable list, which is what the touched-name return is for: the round trip
// asserts the touched set is exactly those three, so a normaliser widened to
// blind rows it should not is caught, and one that silently stopped matching
// reports as one clear failure instead of three confusing row mismatches.
//
// compactRawMessages takes []json.RawMessage, so the single-valued field is
// wrapped and unwrapped HERE rather than growing a second helper. Unwrapping
// keeps the row's dynamic type identical to the record's, so a failure message
// reads as that field's own shape.
//
// ONE DIAGNOSIS TRAP, expected rather than broken. A dropped or `json:"-"`-tagged
// control_request_sent leaves the read-back side nil, and json.Compact over nil
// returns "unexpected end of JSON input" — so that mutant surfaces as
// compactRawMessages' own t.Fatalf, which carries #1662's ticket number and names
// control_responses explicitly. The verdict is correct and the mutant IS red; the
// diagnosis points at the wrong file and the wrong field. The two slice-valued
// fields degrade cleanly to an empty slice and report as ordinary row mismatches.
func compactInitControlRawRows(t *testing.T, rows []initControlFixtureField) ([]initControlFixtureField, []string) {
	t.Helper()

	out := make([]initControlFixtureField, 0, len(rows))
	touched := make([]string, 0, len(rows))
	for _, row := range rows {
		switch v := row.value.(type) {
		case json.RawMessage:
			row.value = compactRawMessages(t, []json.RawMessage{v})[0]
			touched = append(touched, row.name)
		case []json.RawMessage:
			row.value = compactRawMessages(t, v)
			touched = append(touched, row.name)
		}
		out = append(out, row)
	}
	return out, touched
}

// --- the round trip -------------------------------------------------------------

// TestInitControlFixture_RoundTripsEveryFieldIntoOneNamedEntry is #1702's AC 2 and
// AC 3: every field of #1701's fully-populated record survives
// write-then-read-back, and the target directory afterwards holds exactly one
// entry, named exactly what initControlArmFixtureName mints from the record's own
// claude_version and arm.
//
// The subtests share one written artifact and are deliberately NOT parallel; the
// parent owns the tempdir.
//
// It does not restate #1701's properties. Non-zero and same-typed distinctness
// ship in TestInitControlFullRecord_PinsEveryFieldAndTheSluggableVersionToken and
// are preconditions this test consumes rather than assertions it repeats — and
// there is no cap row, because the fixture's capture is far under the cap and
// that row is TestInitControlFixture_WriterCapsStderrCapture's whole subject.
func TestInitControlFixture_RoundTripsEveryFieldIntoOneNamedEntry(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	rec := initControlFullRecord()
	// The offline construction, written inline at each caller rather than behind a
	// local helper: it is one short expression, it is the spelling the sibling
	// family already uses, and inline keeps "this reads no environment" visible at
	// the site this file's finOfflineExecBans entry protects.
	path := writeInitControlFixture(t, dir, dropcapScanner{needles: dropcapFixedNeedles()}, rec)

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("#1702: read back the fixture for claude_version %q: %v", rec.ClaudeVersion, err)
	}
	var got initControlFixtureRecord
	if err := json.Unmarshal(data, &got); err != nil {
		t.Fatalf("#1702: decode the fixture for claude_version %q: %v", rec.ClaudeVersion, err)
	}

	// Both sides go through the SAME listing, applied to the written record and
	// to its decode. There is deliberately no length guard before the zip: both
	// slices come from one function over one struct type, so a divergence is
	// impossible and the guard could never redden.
	want, touched := compactInitControlRawRows(t, initControlFixtureFields(rec))
	have, _ := compactInitControlRawRows(t, initControlFixtureFields(&got))

	t.Run("every field survives the round trip", func(t *testing.T) {
		for i := range want {
			if !reflect.DeepEqual(want[i].value, have[i].value) {
				// Printing both values is safe HERE AND ONLY HERE: every value in
				// this record is a #1701 synthetic literal, and the diagnostic is
				// worth far more than protecting a 53-byte fixture string. #1688
				// fills this same record from a live child and must not inherit
				// the pattern — its stderr_capture is real, bounded child output,
				// and TestInitControlFixture_WriterCapsStderrCapture's rows report
				// lengths and a short prefix for exactly that reason.
				t.Errorf("#1702: %s did not survive the round trip: wrote %v, read back %v; "+
					"#1688 commits this record as its only durable trace",
					want[i].name, want[i].value, have[i].value)
			}
		}
	})

	t.Run("the normaliser touches exactly the three raw-JSON rows", func(t *testing.T) {
		// The type-scoped selection above is what keeps a fourth raw-JSON field
		// covered automatically; this is what keeps that scoping honest. Sorted
		// because the claim is about the SET of rows, not the listing's order.
		wantTouched := []string{"control_request_sent", "control_responses", "stdout_events"}
		gotTouched := append([]string(nil), touched...)
		sort.Strings(gotTouched)

		if !reflect.DeepEqual(gotTouched, wantTouched) {
			t.Errorf("#1702: the normaliser touched %v, want exactly %v: widened, it blinds more "+
				"than the whitespace json.MarshalIndent introduces and a genuinely altered row "+
				"reads back equal; narrowed, it reddens against an honest writer because an "+
				"embedded raw message is never byte-equal after a round trip",
				gotTouched, wantTouched)
		}
	})

	// One assertion, four hazards: a .tmp stranded beside the target by a copy
	// instead of a rename, any stray file, a write that escaped to the package's
	// real testdata/ (which leaves this tempdir at ZERO entries — the
	// relative-path hazard no AST ban can close), and a writer that minted its
	// target name some other way instead of calling initControlArmFixtureName —
	// which since #1722 covers a writer left on the one-input initControlFixtureName,
	// one interpolating its own "initialize_control_v%s_%s.json", and one passing a
	// hardcoded arm instead of the record's.
	//
	// The last is non-vacuous only because BOTH columns of #1701's fixture carry a
	// literal versionSlug rewrites: claude_version's uppercase run and arm's. Against
	// a slug-clean token it is 0-red on the version column; against a clean declared
	// arm it is 0-red on the arm column, which is the whole reason that literal is
	// "after_completed_turn-FIXTURE" and not a declared arm.
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("#1702: list the fixture directory for claude_version %q: %v", rec.ClaudeVersion, err)
	}
	names := make([]string, 0, len(entries))
	for _, e := range entries {
		names = append(names, e.Name())
	}
	wantName := initControlArmFixtureName(rec.ClaudeVersion, rec.Arm)
	if len(names) != 1 || names[0] != wantName {
		t.Errorf("#1702: the target directory holds %q, want exactly [%q]: a .tmp left here is a "+
			"half-written fixture a later commit would pick up, an empty directory means the "+
			"bytes went somewhere the caller never chose, and a differently-spelled entry means "+
			"the writer formats its own name, or hardcodes an arm, instead of minting through "+
			"initControlArmFixtureName from the record's own claude_version and arm",
			names, wantName)
	}
}

// --- the unanswered wait ------------------------------------------------------------

// TestInitControlFixture_RoundTripsAnUnansweredWaitBesideCapturedBytes is #1722's
// second half: a record carrying captured response bytes AND
// control_response_within_wait FALSE is representable, and it survives a write and
// a read-back carrying both halves.
//
// THAT PAIR IS THE WHOLE POINT, and it is reachable on the live path rather than
// hypothetical. runInitControlChild's setModeWaitFor returns when its budget
// expires, and ControlResponses is snapshotted much later — after stdinPipe.Close()
// and cmd.Wait(). A response landing in that window is captured with the wait
// already false. "There are response bytes" and "the wait was satisfied" are two
// different facts, and before #1722 only the first survived the run.
//
// It is the SOLE red for a control_response_within_wait derived from
// len(ControlResponses) > 0 instead of from the wait's own result. The main round
// trip cannot catch that mutant: initControlFullRecord carries the COHERENT pair —
// bytes and a satisfied wait — because a bool is non-zero only when true, so
// #1701's non-zero property forbids the discriminating case there. Hence a second
// record instance here rather than a change to the fixture.
//
// The failure messages report the two field names and a response COUNT, never the
// response bytes. runInitControlChild fills this same record from a live child, and
// this file's sibling rows deliberately report lengths and short prefixes for that
// reason; this must not be the site that breaks the pattern.
func TestInitControlFixture_RoundTripsAnUnansweredWaitBesideCapturedBytes(t *testing.T) {
	t.Parallel()

	// A fresh pointer, mutated here and shared with nothing: initControlFullRecord
	// is a function and not a package-level var precisely so this and the cap test's
	// parallel subtests cannot race on one record.
	rec := initControlFullRecord()
	rec.ControlResponseWithinWait = false

	// The vacuity control, and it must Fatalf rather than skip — precheck's
	// precedent in the cap test below. If a later edit empties the fixture's
	// responses, this row stops discriminating between "the field is measured" and
	// "the field is always false" while still passing, and a row that cannot
	// discriminate is a broken instrument.
	if len(rec.ControlResponses) == 0 {
		t.Fatalf("#1722: the fixture carries no control_responses, so asserting " +
			"control_response_within_wait==false beside captured bytes proves nothing: the " +
			"derived-from-the-count mutant reads back false here too and this test goes 0-red")
	}

	path := writeInitControlFixture(t, t.TempDir(), dropcapScanner{needles: dropcapFixedNeedles()}, rec)
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("#1722: read back the fixture for claude_version %q arm %q: %v",
			rec.ClaudeVersion, rec.Arm, err)
	}
	var back initControlFixtureRecord
	if err := json.Unmarshal(data, &back); err != nil {
		t.Fatalf("#1722: decode the fixture for claude_version %q arm %q: %v",
			rec.ClaudeVersion, rec.Arm, err)
	}

	// Both halves are needed and neither catches the other's mutant: the first is
	// the claim, the second is what makes the first mean something other than "the
	// field is always false".
	if back.ControlResponseWithinWait {
		t.Errorf("#1722: control_response_within_wait reads back true from a record written "+
			"with it false and %d control_responses captured; that is a field derived from "+
			"the response count instead of from the bounded wait's own result, and the main "+
			"round trip — which carries the coherent pair — stays green over it",
			len(back.ControlResponses))
	}
	if len(back.ControlResponses) == 0 {
		t.Errorf("#1722: control_responses reads back with %d entries, want the %d written; "+
			"without captured bytes on the other side, control_response_within_wait==false "+
			"above is satisfied by a field that is simply always false",
			len(back.ControlResponses), len(rec.ControlResponses))
	}
}

// --- the census -----------------------------------------------------------------

// TestInitControlFixture_DistinguishesAnEmptyCensusFromAnAbsentOne is #1731's
// second criterion: a record that RAN the redaction and needed none writes
// DIFFERENT bytes than one that never ran it, so a reader of a committed fixture
// cannot take "nothing needed redacting" for "the redactor was skipped".
//
// The whole distinction is `[]` versus `null`. dropcapRedactor.substitutions
// returns a NON-NIL EMPTY slice when nothing fired while an unfilled field is
// nil, and this record carries no `omitempty` on any tag, so the two marshal
// differently. It is one tag and one nil-normalising helper away from gone, and
// nothing else in this package notices either: scanInitControlFixture's
// `out := *rec` is a shallow copy that preserves nil-ness today, so the
// distinction reaches the file intact while every other row here stays green.
//
// THROUGH THE WRITER RATHER THAN A BARE json.Marshal, deliberately. The two
// mutants are an `omitempty` on the tag and a helper that normalises nil to empty
// ON THE WAY TO THE FILE; marshalling here directly catches only the first, and
// the writer's own marshal is what produces the bytes a reviewer of a committed
// artifact actually reads. It lands in this file rather than the record's or the
// redaction file's for the reason #1722's row does: it writes and reads back, and
// this is the file whose finOfflineExecBans entry permits os.WriteFile and
// os.ReadFile. The TestInitControlFixture_ prefix is load-bearing — this file's
// header documents a -run filter that keys on it.
//
// Deliberately NO bytes.Contains assertion pinning `"redaction": []` against
// `"redaction": null`. Inequality already reddens for every mutant in the class —
// an `omitempty` drops the key from BOTH sides, a nil-normaliser renders `[]` on
// both, a `json:"-"` drops it from both — and a literal-spelling assertion would
// additionally pin json.MarshalIndent's whitespace, which is not this row's
// subject.
//
// WHAT IT DOES NOT MEASURE, so that nobody credits it with more than it proves:
// it catches a writer-side helper that turns a NIL census non-nil. It does NOT
// catch a writer that overwrites a non-nil census with a DIFFERENT value, and
// nothing in #1731 does — that half rests on the copy-and-don't-mutate contract,
// now scanInitControlFixture's, whose byte-identity instrument #1748 shipped inside
// TestInitControlFixture_WriterCapsStderrCapture.
func TestInitControlFixture_DistinguishesAnEmptyCensusFromAnAbsentOne(t *testing.T) {
	t.Parallel()

	// The same construction TestInitControlRedactRecord_LeavesAPathFreeRecordByteIdentical
	// uses — the same constructor over the same four synthetic values — so the two
	// rows stay in step rather than drifting into two different redactors. Neither
	// value is read off the environment, which is what keeps this file's ban on
	// realHome and os.TempDir untouched.
	rec := initControlFullRecord()
	red := newInitControlRedactor(
		initControlOperatorHomeValue,
		initControlTempHomeValue,
		initControlWorkdirValue,
		initControlTempDirValue,
	)
	census := redactInitControlRecord(red, rec)

	// The vacuity controls, and they must Fatalf rather than skip — precheck's
	// precedent in the cap test below. Two distinct failures, so two messages: a
	// property that cannot discriminate is a broken instrument, not a passing test.
	if census == nil {
		t.Fatalf("#1731: the pass returned a NIL census over a path-free record, so this row " +
			"compares nil against nil and `[]` versus `null` is no longer a distinction " +
			"anywhere: dropcapRedactor.substitutions stopped returning a NON-NIL EMPTY slice, " +
			"and that non-nil-ness is the entire mechanism the redaction field carries")
	}
	if len(census) != 0 {
		t.Fatalf("#1731: the pass fired %d class(es) over initControlFullRecord, so this row "+
			"compares a POPULATED census against nil and settles nothing about the EMPTY "+
			"case it exists for; that fixture acquired a path value, which also reddens "+
			"TestInitControlRedactRecord_LeavesAPathFreeRecordByteIdentical", len(census))
	}

	// Two shallow copies of the POST-PASS record, differing in exactly one field
	// and leaning on no other row's byte-identity claim. Only the new field is
	// assigned on either copy, so no slice field's backing array is touched and the
	// fresh pointer initControlFullRecord hands out stays unshared.
	ran := *rec
	ran.Redaction = census
	skipped := *rec
	skipped.Redaction = nil

	// A tempdir EACH, and not stylistic: both copies carry the same claude_version
	// and the same arm, so initControlArmFixtureName mints one filename for both
	// and a shared directory would have them overwrite each other.
	// Built ONCE above the closure and captured. dropcapScanner is append-only
	// during construction and read-only afterwards — scan is a value receiver that
	// allocates its own results — so one value serves both writes; see
	// runInitControlChild's doc, which states exactly this asymmetry against the
	// redactor. It reads no environment, which is what keeps this file's ban on
	// newDropcapScanner and realHome untouched.
	scanner := dropcapScanner{needles: dropcapFixedNeedles()}
	write := func(rec *initControlFixtureRecord) []byte {
		t.Helper()
		path := writeInitControlFixture(t, t.TempDir(), scanner, rec)
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("#1731: read back the fixture for claude_version %q arm %q: %v",
				rec.ClaudeVersion, rec.Arm, err)
		}
		return data
	}
	ranBytes := write(&ran)
	skippedBytes := write(&skipped)

	if bytes.Equal(ranBytes, skippedBytes) {
		// Printing both blobs is the same narrowly-scoped exception the round-trip
		// and byte-identity rows already take: every value in this record is a
		// synthetic literal, and the diagnostic is worth more than the bytes.
		// runInitControlChild fills this same record from a live child and must not
		// inherit the pattern.
		t.Errorf("#1731: a record whose redaction pass fired NOTHING wrote bytes identical to "+
			"one that never ran the pass, so a reader of a committed fixture cannot tell "+
			"\"nothing needed redacting\" from \"the redactor was skipped\": an `omitempty` on "+
			"the redaction tag drops the key from both sides, and a helper that normalises nil "+
			"to empty on the way to the file renders `[]` on both.\nran     %s\nskipped %s",
			ranBytes, skippedBytes)
	}
}

// --- the arming census ---------------------------------------------------------------

// TestInitControlFixture_DistinguishesAnArmedNothingScanFromAnAbsentOne is #1747's
// second criterion, and it is the census row above for the other field: a record
// whose scanner was BUILT and armed nothing writes DIFFERENT bytes than one that
// never reached the fill site, so a reader of a committed fixture cannot take "no
// class armed" for "the field was never filled".
//
// The whole distinction is `{}` versus `null`. dropcapScanner.applied returns a
// NON-NIL EMPTY map when no needle was appended while an unfilled field is nil, and
// this record carries no `omitempty` on any tag, so the two marshal differently.
// It is one tag and one nil-normalising helper away from gone, and nothing else in
// this package notices either: scanInitControlFixture's `out := *rec` is a shallow
// copy that preserves nil-ness today.
//
// The armed-nothing side is built from dropcapScanner{}.applied() rather than from
// a map[string]bool{} literal. The non-nil-ness of that return is the entire
// mechanism the distinction rests on, and a literal would pin this test's own value
// instead of the production one. initControlScanApplied cannot serve here either:
// by construction it always adds the four path classes and can never return empty.
//
// THROUGH THE WRITER RATHER THAN A BARE json.Marshal, and with deliberately NO
// bytes.Contains assertion pinning the spelling — both for the reasons
// TestInitControlFixture_DistinguishesAnEmptyCensusFromAnAbsentOne states. It lands
// in this file for that row's reason too, and the TestInitControlFixture_ prefix is
// load-bearing: this file's header documents a -run filter that keys on it.
//
// WHAT IT DOES NOT MEASURE: it catches a writer-side helper that turns a NIL map
// non-nil. It does NOT catch a writer that overwrites a non-nil map with a
// DIFFERENT value — a writer that FILTERED the armed-nothing classes out on the way
// to disk is invisible here, because neither side of this comparison carries an
// entry at all; initControlFullRecord's false-valued entry and
// TestInitControlFixture_RoundTripsEveryFieldIntoOneNamedEntry are what catch that
// one, per note 8 on that fixture. And the `null` side is genuinely reachable in
// the committed corpus: every fixture predating this field decodes with a nil map,
// which is what makes the distinction worth bytes.
func TestInitControlFixture_DistinguishesAnArmedNothingScanFromAnAbsentOne(t *testing.T) {
	t.Parallel()

	// A zero scanner has no needles, so applied() ranges nothing and returns its
	// non-nil empty map. This file's finOfflineExecBans entry stays untouched:
	// nothing here reads the environment, which newDropcapScanner would.
	armedNothing := dropcapScanner{}.applied()

	// The vacuity controls, and they must Fatalf rather than skip — the cap test
	// below is the precedent. Two distinct failures, so two messages: a property that
	// cannot discriminate is a broken instrument, not a passing test.
	if armedNothing == nil {
		t.Fatalf("#1747: dropcapScanner.applied returned NIL over a scanner with no needles, so " +
			"this row compares nil against nil and `{}` versus `null` is no longer a distinction " +
			"anywhere: that non-nil-ness is the entire mechanism credential_scan_applied carries")
	}
	if len(armedNothing) != 0 {
		t.Fatalf("#1747: dropcapScanner.applied returned %d entr(ies) over a scanner with NO "+
			"needles, so this row compares a POPULATED map against nil and settles nothing about "+
			"the armed-nothing case it exists for", len(armedNothing))
	}

	// Two shallow copies of one record, differing in exactly one field and leaning on
	// no other row's byte-identity claim. Only the new field is assigned on either
	// copy, so no slice field's backing array is touched and the fresh pointer
	// initControlFullRecord hands out stays unshared.
	rec := initControlFullRecord()
	ran := *rec
	ran.CredentialScanApplied = armedNothing
	skipped := *rec
	skipped.CredentialScanApplied = nil

	// A tempdir EACH, and not stylistic: both copies carry the same claude_version
	// and the same arm, so initControlArmFixtureName mints one filename for both and
	// a shared directory would have them overwrite each other.
	// Built ONCE above the closure and captured, for the reason the census row
	// above states: dropcapScanner is read-only after construction, and this
	// construction reads no environment.
	scanner := dropcapScanner{needles: dropcapFixedNeedles()}
	write := func(rec *initControlFixtureRecord) []byte {
		t.Helper()
		path := writeInitControlFixture(t, t.TempDir(), scanner, rec)
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("#1747: read back the fixture for claude_version %q arm %q: %v",
				rec.ClaudeVersion, rec.Arm, err)
		}
		return data
	}
	ranBytes := write(&ran)
	skippedBytes := write(&skipped)

	if bytes.Equal(ranBytes, skippedBytes) {
		// Printing both blobs is the same narrowly-scoped exception the round-trip and
		// byte-identity rows already take: every value in this record is a synthetic
		// literal. runInitControlChild fills this same record from a live child and
		// must not inherit the pattern.
		t.Errorf("#1747: a record whose scanner armed NOTHING wrote bytes identical to one whose "+
			"field was never filled, so a reader of a committed fixture cannot tell \"no class "+
			"armed\" from \"the scanner never ran\": an `omitempty` on the credential_scan_applied "+
			"tag drops the key from both sides, and a helper that normalises nil to empty on the "+
			"way to the file renders `{}` on both.\nran     %s\nskipped %s", ranBytes, skippedBytes)
	}
}

// --- the planted credential ------------------------------------------------------

// initControlPlantedPath is the synthetic operator path AC 3's row plants. It is a
// FIXED deny class (/Users/), armed on every scanner and exempt from
// dropcapMinNeedle by construction — a dynamic needle shorter than that minimum
// arms nothing, so a row planting one is green and proves nothing.
// initControlTempDirValue (/synthetic/tmp) is 14 bytes and would be skipped;
// initControlTempHomeValue and initControlOperatorHomeValue are long enough but are
// not armed on the fixed-only offline scanner at all.
const initControlPlantedPath = "/Users/synthetic-operator/Library/Logs/shim.log"

// TestInitControlFixture_ScanRefusesAPlantedCredential is #1748's AC 3: a record
// carrying a planted value of an armed class is refused, and the refusal names the
// class that hit.
//
// IT EXERCISES THE SCAN OVER THE MARSHALLED RECORD, NEVER writeInitControlFixture's
// FATAL — the sibling family's resolution for the same shape, where
// dropcapWriteRecord's net is proved by TestDropcapRedactAndScan's "the net is not
// decorative" subtest, which marshals its own blob and calls scan. A t.Fatalf from
// the writer takes the calling subtest down with it, there is no fake testing.TB in
// this package and testing.TB cannot be implemented outside testing, so nothing can
// assert on a refusal from inside one. That is also why AC 4 — the refusal prints no
// excerpt, no record dump and no needle value — is discharged by CONSTRUCTION at
// scanInitControlFixture rather than by a row here.
//
// WHAT THIS ROW DOES NOT PROVE, so that nobody credits it with more: it does not
// prove that scanInitControlFixture CALLS scan. That is construction — the step is
// the sole producer of the write's bytes and the scan is inside it — and it is the
// one untestable link in the chain. What it proves is that a fixed-class value
// planted in THIS record's marshalled form IS reported, by name, by the scanner the
// five offline callers pass.
//
// ONE planted class here, deliberately. The per-class sweep is #1749, already wired
// blocked-by this ticket.
//
// It does NOT re-scan the committed testdata/initialize_control_v2.1.239.json, and
// the temptation is real because the sibling family's scanner exists partly so
// offline validation can re-scan a committed capture forever. That file still
// carries three of the five fixed classes — re-measured 2026-08-24: /Users/ once,
// /private/var/folders/ once, /var/folders/ twice, one of those two being the tail
// of the /private/ occurrence — so a row that re-scanned it would be red on arrival.
// #1733's redaction takes effect on the next live capture, which replaces the file.
// The scan this slice ships is on the WRITE PATH ONLY.
//
// The failure messages name class constants and the hits slice. They never print the
// planted value, the blob or the record, so runInitControlChild has no pattern here
// to inherit.
func TestInitControlFixture_ScanRefusesAPlantedCredential(t *testing.T) {
	t.Parallel()

	scanner := dropcapScanner{needles: dropcapFixedNeedles()}

	clean, err := json.MarshalIndent(initControlFullRecord(), "", "  ")
	if err != nil {
		t.Fatalf("#1748: marshal the unplanted fixture: %v", err)
	}
	cleanHits, notApplied := scanner.scan(clean)

	// The vacuity controls, and they must Fatalf rather than skip — the cap test's
	// precedent. Two distinct failures, so two messages: a property that cannot
	// discriminate is a broken instrument, not a passing test.
	//
	// The first is also the one row that says out loud WHY the five offline
	// writeInitControlFixture callers do not fatal: this fixture is path-free.
	// Without it the planted assertion below cannot tell "the plant was seen" from
	// "this fixture always hits".
	if len(cleanHits) != 0 {
		t.Fatalf("#1748: the UNPLANTED fixture already hits %d class(es) %v, so the planted "+
			"assertion below cannot tell \"the plant was seen\" from \"this record always hits\" — "+
			"and the five offline writeInitControlFixture callers, which write this same record, "+
			"are now fataling too", len(cleanHits), cleanHits)
	}
	// The five fixed needles are not dynamic, so dropcapMinNeedle never skips them.
	// If a later edit marked one dynamic, its class would be skipped, the planted
	// assertion below would go green-and-vacuous, and nothing else would notice.
	if len(notApplied) != 0 {
		t.Fatalf("#1748: the offline scanner reports %d class(es) NOT APPLIED %v; every fixed "+
			"needle is exempt from the dropcapMinNeedle minimum by construction, so a skipped one "+
			"means a fixed needle was marked dynamic and the planted assertion below goes "+
			"green-and-vacuous", len(notApplied), notApplied)
	}

	// stderr_capture is the realistic carrier — child stderr is where an operator
	// path shows up, and initialize_control_redaction_test.go's own fixture plants a
	// shim-log path there — and it puts this row in the same field as the
	// byte-identity row above. The planted value goes at the FRONT and the whole
	// capture stays well inside stderrFixtureCap, so the cap cannot move it into a
	// truncated tail.
	rec := initControlFullRecord()
	rec.StderrCapture = initControlPlantedPath + ": child stderr the redaction table did not predict"

	planted, err := json.MarshalIndent(rec, "", "  ")
	if err != nil {
		t.Fatalf("#1748: marshal the planted fixture: %v", err)
	}
	hits, _ := scanner.scan(planted)
	if !dropcapContains(hits, dropcapDenyUsers) {
		t.Errorf("#1748: hits = %v, want %q among them: an operator path planted in stderr_capture "+
			"survived the deny-scan, so writeInitControlFixture would commit it and the fail-closed "+
			"net behind #1733's redaction table is decorative", hits, dropcapDenyUsers)
	}
}

// --- the per-class sweep ----------------------------------------------------------

// The three synthetic needle values #1749 mints. The other three dynamic classes
// reuse initControlTempHomeValue, initControlOperatorHomeValue and
// initControlWorkdirValue, which the redaction family already declares.
//
// Every constraint below is load-bearing, not taste:
//
//   - EACH IS AT LEAST dropcapMinNeedle (16) BYTES. A shorter dynamic needle is
//     skipped, its class reads as not applied, and its row is green-and-vacuous.
//     initControlTempDirValue (/synthetic/tmp) is 14 bytes and is the family
//     constant that fails this — it must never be used as a needle.
//   - NEITHER CREDENTIAL VALUE STARTS WITH sk-ant-, so each credential row
//     isolates its own class from the fixed anthropic-key-prefix class instead of
//     hitting two.
//   - NEITHER CREDENTIAL VALUE IS A SUBSTRING OF THE OTHER, or both credential
//     rows would hit both credential classes and neither would be the sole red for
//     its own.
//   - NEITHER CREDENTIAL VALUE IS A SUBSTRING OF "CLAUDE_CODE_OAUTH_TOKEN" OR
//     "ANTHROPIC_API_KEY". Those two class names are the only armed class names at
//     or above the minimum (23 and 17 bytes), so a needle hiding inside one would
//     make the net hit its own metadata on every run —
//     TestDropcapDenyClassNamesDoNotCarryTheirNeedle guards that hazard for the
//     five FIXED names and does not cover the dynamic six. It bites the moment a
//     record carries the eleven-class arming census; initControlFullRecord's
//     credential_scan_applied map carries workdir (7) and artifact_dir (12), both
//     under the minimum, so it is safe today and this constraint is what keeps it
//     safe if that map ever grows.
//   - THE ARTIFACT-DIR VALUE IS NOT NESTED UNDER THE TEMP-HOME VALUE. It shares
//     only /synthetic/tmp, which no class arms, so its row hits exactly one class.
//     initControlWorkdirValue is the counter-example the table below records: it
//     IS nested, and its row legitimately hits three.
//   - NO VALUE CONTRIBUTES A SEGMENT NEEDLE. addDynamicPath also arms every '/'-
//     or '-'-separated segment at least dropcapMinNeedle bytes long; the longest
//     segment across all four paths is "synthetic" (9), so today none does. A
//     newly invented value with a long segment would change the hit sets recorded
//     on the rows below.
const (
	initControlSyntheticOAuthToken  = "synthetic-oauth-token-not-a-real-credential"
	initControlSyntheticAPIKey      = "synthetic-api-key-not-a-real-credential"
	initControlSyntheticArtifactDir = "/synthetic/tmp/artifacts"
)

// initControlPlantSuffix is the trailing free text every planted stderr_capture
// carries, and IT MUST NOT BEGIN WITH '/'. Appending a path segment synthesises
// needles the planted value alone does not carry: initControlTempHomeValue + "/x"
// is /synthetic/tmp/home/x, which contains the fixed /home/ literal and turns a
// one-class row into a two-class one. This is the shape #1748's row already plants.
const initControlPlantSuffix = ": child stderr the redaction table did not predict"

// newInitControlOfflineScanner mirrors the eleven classes newDropcapScanner arms,
// from synthetic constants only: the same five arming calls in the same order, then
// dropcapFixedNeedles wholesale, with that constructor's two os.Getenv reads and its
// realHome read replaced by declared values.
//
// The substitution is the point rather than a convenience. A table built through the
// real constructor arms the OPERATOR's environment — it stores two live credentials
// as needle values and takes $HOME as operator_home — so every row would be green or
// red depending on whose machine ran it. This file's finOfflineExecBans entry bans
// both names for exactly that reason, and the ban is an AST identifier match, so it
// cannot be answered out of a comment.
//
// The returned scanner reads nothing from the environment, the filesystem or the
// clock, and is read-only after construction — the property
// TestInitControlFixture_DistinguishesAnArmedNothingScanFromAnAbsentOne already
// leans on — so one instance is safely shared by every parallel row.
func newInitControlOfflineScanner() dropcapScanner {
	s := dropcapScanner{}
	s.addDynamic("CLAUDE_CODE_OAUTH_TOKEN", initControlSyntheticOAuthToken)
	s.addDynamic("ANTHROPIC_API_KEY", initControlSyntheticAPIKey)
	s.addDynamicPath(dropcapClassTempHome, initControlTempHomeValue)
	s.addDynamicPath(dropcapClassOperatorHome, initControlOperatorHomeValue)
	s.addDynamicPath(dropcapClassArtifactDir, initControlSyntheticArtifactDir)
	s.addDynamicPath(dropcapClassWorkdir, initControlWorkdirValue)
	s.needles = append(s.needles, dropcapFixedNeedles()...)
	return s
}

// TestInitControlFixture_ScanRefusesAPlantedValueOfEveryArmedClass is #1749: one row
// per class the scanner arms, each planting a value of that class into the record
// and asserting the class is among the scan's hits. #1748 shipped ONE planted row
// and said so out loud; this is the sweep it deferred, and it turns "the net works"
// into a table rather than a claim about ten classes nobody measured.
//
// IT EXERCISES THE SCAN OVER THE MARSHALLED RECORD, NEVER writeInitControlFixture's
// FATAL, for the reason TestInitControlFixture_ScanRefusesAPlantedCredential states
// at length: a t.Fatalf from the writer takes the calling subtest down with it,
// there is no fake testing.TB in this package and testing.TB cannot be implemented
// outside testing, so nothing can assert on a refusal from inside one. The assertion
// is still on the DECIDING VALUE rather than on a proxy — scanInitControlFixture
// refuses iff len(hits) > 0.
//
// ONE PLANT SITE PER ROW IS ENOUGH, and the reason is structural rather than a
// budget: scan reads the WHOLE marshalled blob, so field coverage comes for free and
// a per-field table would separate nothing. redactInitControlRecord is the opposite
// case — it visits fields BY NAME, which is why the redaction family does need
// per-field rows.
//
// # What this table does not prove, so that nobody credits it with more
//
//   - That scanInitControlFixture CALLS scan. That is construction, and the one
//     untestable link, per the paragraph above.
//   - That newInitControlOfflineScanner arms the same class SET as
//     newDropcapScanner. The four path classes come from the shared dropcapClass*
//     constants and the five fixed classes from dropcapFixedNeedles() wholesale, so
//     those nine cannot drift. The two credential class names are spelled as string
//     literals in both files, and that is the entire drift surface. They are spelled
//     INDEPENDENTLY in the builder and in the table below for what that is worth: a
//     typo on one side reddens — the row misses its class, or the builder arms a
//     class no row claims — while a typo made identically in both is invisible here.
//   - The SLUG spellings. Every row plants a raw value, so addDynamicPath's slug
//     half is never exercised; TestDropcapRedactionAndDenyScan's slug-mangled
//     subtest is where that already lives.
//   - Anything about the committed testdata/initialize_control_v2.1.239.json. Do NOT
//     add a row that re-scans it: re-measured 2026-08-25, it still carries /Users/
//     once, /private/var/folders/ once and /var/folders/ twice, one of those two
//     being the tail of the /private/ occurrence, so such a row is red on arrival.
//     #1733's redaction takes effect on the next live capture, which replaces the
//     file.
//
// The failure messages name class constants and the hits and applied values. They
// never print a needle, the needle slice, the scanner or a planted value — the rule
// scanInitControlFixture's doc states for every line added to this file. Every value
// here is synthetic, so printing one would leak nothing; the point is that the live
// callers inherit no pattern worth copying.
func TestInitControlFixture_ScanRefusesAPlantedValueOfEveryArmedClass(t *testing.T) {
	t.Parallel()

	scanner := newInitControlOfflineScanner()

	rows := []struct {
		class string
		plant string
	}{
		// The two credential classes. Their names are literals here, spelled
		// independently of the builder's, per the drift note above.
		{class: "CLAUDE_CODE_OAUTH_TOKEN", plant: initControlSyntheticOAuthToken},
		{class: "ANTHROPIC_API_KEY", plant: initControlSyntheticAPIKey},

		// The four dynamic path classes.
		{class: dropcapClassTempHome, plant: initControlTempHomeValue},
		{class: dropcapClassOperatorHome, plant: initControlOperatorHomeValue},
		{class: dropcapClassArtifactDir, plant: initControlSyntheticArtifactDir},
		// MEASURED, THREE CLASSES, and nobody should "fix" it:
		// /synthetic/tmp/home/work contains initControlTempHomeValue AND the fixed
		// /home/ literal, so this row hits home-path-prefix, temp_home and workdir.
		// That is why every row below asserts CONTAINMENT and never equality — an
		// equality assertion here is red on arrival. Containment still leaves this
		// row red when the workdir needle is dropped, which is what it is for.
		{class: dropcapClassWorkdir, plant: initControlWorkdirValue},

		// The five fixed classes. initControlPlantedPath is #1748's plant, reused
		// verbatim rather than duplicated into a second /Users/ constant.
		{class: dropcapDenySkAnt, plant: "sk-ant-synthetic-not-a-real-key"},
		{class: dropcapDenyUsers, plant: initControlPlantedPath},
		{class: dropcapDenyHome, plant: "/home/synthetic-operator/.claude/logs/shim.log"},
		// MEASURED, TWO CLASSES: /private/var/folders/ carries /var/folders/ as its
		// own tail, so this row hits var-folders-prefix too. Containment again.
		{class: dropcapDenyPVarF, plant: "/private/var/folders/sy/synthetic/T/shim.log"},
		{class: dropcapDenyVarF, plant: "/var/folders/sy/synthetic/T/shim.log"},
	}

	// The arming check, once over the shared scanner and therefore a per-row fact:
	// every class the table claims is a class this scanner ACTUALLY ARMED. A row
	// whose needle was skipped is green and settles nothing, which is why this is a
	// criterion of its own rather than prose.
	//
	// scan's second return is discarded throughout, unlike in #1748's row, and the
	// divergence is a decision rather than an oversight: notApplied reports the
	// short-needle case ONLY, while applied() reports that case AND the
	// absent-class case. An assertion on notApplied would be red only where the
	// !armed check below is already red — dead weight, not a second net.
	applied := scanner.applied()

	// Set-size equality, which together with the per-row presence check below makes
	// the table's eleven and the builder's armed eleven the SAME SET. Sole red for a
	// twelfth class added to the builder with no row behind it.
	if len(applied) != len(rows) {
		t.Fatalf("#1749: the offline scanner armed %d class(es) %v while the table carries %d "+
			"row(s); the two must be the same set, or a class the scan arms has no row behind "+
			"it and this table's per-class coverage is short by one",
			len(applied), applied, len(rows))
	}

	// Two defects, two messages: absent-entirely and present-but-false are different
	// failures and a single combined assertion cannot say which happened. The absent
	// case is reachable rather than theoretical — addDynamicPath("") goes through
	// dropcapPathSpellings, which returns nil for the empty string, so no needle is
	// appended and the class never reaches the map at all. That is the arm
	// TestInitControlScanApplied_RecordsAnArmedNothingClassForAnAbsentPath exists
	// for, and the one a "did anything come back skipped" check would miss.
	for _, row := range rows {
		armed, ok := applied[row.class]
		if !ok {
			t.Fatalf("#1749: the offline scanner's applied() omits %q ENTIRELY (armed %v), so the "+
				"table claims a class no needle was ever built for — an empty path handed to "+
				"addDynamicPath appends nothing and the class silently leaves the census",
				row.class, applied)
		}
		if !armed {
			t.Errorf("#1749: the offline scanner reports %q as ARMED-NOTHING (armed %v), so its "+
				"needle is under the dropcapMinNeedle minimum and was skipped; that row's "+
				"assertion below is green-and-vacuous", row.class, applied)
		}
	}

	// The clean-record control, and it is load-bearing rather than tidiness: without
	// it a scanner that reported EVERY class on EVERY input would pass all eleven
	// planted rows. It is also the vacuity control for the whole table at once —
	// zero hits over the clean record is exactly the statement that no row's plant
	// was already present in the fixture, proved for eleven classes in one assertion
	// instead of eleven. Fatal rather than skip: a property that cannot discriminate
	// is a broken instrument, not a passing test.
	clean, err := json.MarshalIndent(initControlFullRecord(), "", "  ")
	if err != nil {
		t.Fatalf("#1749: marshal the unplanted fixture: %v", err)
	}
	if cleanHits, _ := scanner.scan(clean); len(cleanHits) != 0 {
		t.Fatalf("#1749: the UNPLANTED fixture already hits %d class(es) %v against the "+
			"eleven-class offline scanner, so the planted rows below cannot tell \"the plant was "+
			"seen\" from \"this record always hits\"", len(cleanHits), cleanHits)
	}

	for _, row := range rows {
		t.Run(row.class, func(t *testing.T) {
			t.Parallel()

			// stderr_capture is the carrier for the reason #1748's row chose it:
			// child stderr is where an unpredicted operator path actually shows up.
			// The plant goes at the FRONT and the whole capture stays well inside
			// stderrFixtureCap, so no cap can move it into a truncated tail.
			rec := initControlFullRecord()
			rec.StderrCapture = row.plant + initControlPlantSuffix

			planted, err := json.MarshalIndent(rec, "", "  ")
			if err != nil {
				t.Fatalf("#1749: marshal the fixture planted for class %q: %v", row.class, err)
			}
			hits, _ := scanner.scan(planted)
			if !dropcapContains(hits, row.class) {
				t.Errorf("#1749: hits = %v, want %q among them: a value of that class planted in "+
					"stderr_capture survived the deny-scan, so writeInitControlFixture would commit "+
					"it and the fail-closed net behind #1733's redaction table covers ten of the "+
					"eleven classes it arms", hits, row.class)
			}
		})
	}
}

// --- the cap ------------------------------------------------------------------------

// TestInitControlFixture_WriterCapsStderrCapture is #1700: writeInitControlFixture
// bounds the free-text capture, so #1688 cannot forget to. stderr_capture absorbs
// unbounded text from a process this repo does not control, and the file it lands
// in gets committed.
//
// capFixtureCapture is already proven by #1662's own cap test. What is proven here
// is different and unreachable by calling that helper: that THIS writer calls it,
// on THE RIGHT FIELD, and that the bound survives a write and a read-back FROM
// DISK. Every assertion therefore runs over the bytes read out of the written file
// — a direct call to capFixtureCapture inside an assertion collapses the
// cap-omitted and wrong-field mis-implementations to green, because it cannot
// catch a writer that never applied the cap at all. Every length assertion is on
// len(), never on rune count: the cap is a byte cap and truncateString slices
// bytes.
//
// # Why two rows, and why neither is dead weight
//
// Each row is the sole red for a distinct mis-implementation, measured through
// json.MarshalIndent and back:
//
//   - Calling truncateString(s, stderrFixtureCap) directly instead of
//     capFixtureCapture: the multi-byte row reads back at 8194, over the bound the
//     writer states, and is RED — SOLE. encoding/json does not error on invalid
//     UTF-8, it substitutes U+FFFD at three bytes per invalid byte, so a byte cap
//     with no rune-boundary trim reads back OVER its own cap. The ASCII row, where
//     a byte cut is a rune cut, stays perfectly green.
//   - A trim that removes one byte too many: the ASCII row reads back at 8191 and
//     is RED — SOLE. That is why the ASCII assertion must be EXACT while the
//     multi-byte one can only be a RANGE — the rune-boundary trim legitimately
//     removes up to utf8.UTFMax-1 bytes, so a range is the strongest claim the
//     multi-byte row can make and an over-trim hides inside it.
//   - A writer that caps the caller's record instead of a copy: only the
//     no-mutation check is RED — SOLE.
//
// There is deliberately no under-cap row. Both capFixtureCapture and
// truncateString carry a len(s) <= max early return, so an under-cap input reddens
// nothing; #1662's header records that as measured. Two cases, not three.
//
// #1748 added a THIRD claim to this loop body rather than a third row, and for the
// same vacuity reason: the disk bytes must be the bytes the deny-scan passed, which
// is a distinction only an over-cap record can make. It reads
// scanInitControlFixture's no-filesystem-call property from the other end — see the
// comment at the assertion itself.
//
// # Do not print the capture
//
// Failure messages report LENGTHS, the cap constant, the row's diagnosis and at
// most a 16-byte prefix. A %q of want/got here dumps up to stderrFixtureCap bytes
// of child output into an unbounded -v run log, which defeats the field's entire
// purpose. The 16-byte prefix is safe only because this test's literals are
// synthetic; #1688 must not inherit even that much.
func TestInitControlFixture_WriterCapsStderrCapture(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		capture string
		// precheck asserts a property of this row's OWN literal that the row's
		// ability to discriminate depends on. nil where the row has none.
		//
		// This is a deliberate divergence from
		// TestPoolRevokeFixture_WriterCapsChildOutputCapture, which guards the
		// same property with an `if tc.name == …` branch in the loop body. A
		// name-string match stops firing silently if anyone renames the row,
		// which is exactly the class of silent degradation the control exists to
		// prevent.
		precheck func(t *testing.T, capture string)
		check    func(t *testing.T, capture, back string)
	}{
		{
			name:    "over_cap_ascii",
			capture: strings.Repeat("A", stderrFixtureCap+1024),
			check: func(t *testing.T, capture, back string) {
				// EXACT, not a range: this is the sole red for a trim that removes
				// one byte too many, and a range here would swallow it.
				if len(back) != stderrFixtureCap {
					t.Errorf("#1700: a %d-byte capture reads back at %d bytes, want exactly %d; "+
						"the writer leaves the cap to its caller, or trims past the boundary, "+
						"and #1688 then commits an unbounded credential-bearing dump",
						len(capture), len(back), stderrFixtureCap)
				}
			},
		},
		{
			// One ASCII byte then two-byte runes, so rune starts land on odd byte
			// indices and the byte at stderrFixtureCap is a CONTINUATION byte —
			// truncateString alone would split a rune here.
			name:    "over_cap_multibyte",
			capture: "A" + strings.Repeat("é", 5000),
			precheck: func(t *testing.T, capture string) {
				// The vacuity control, and it must Fatalf rather than skip: if a
				// later edit to the literal moves the boundary onto a rune start,
				// truncateString alone no longer splits a rune, the
				// direct-truncateString mis-implementation goes green, and this
				// row proves nothing while still passing. A row that cannot
				// discriminate is a broken instrument, not a passing test.
				if utf8.RuneStart(capture[stderrFixtureCap]) {
					t.Fatalf("#1700: byte %d of this row's %d-byte capture starts a rune, so "+
						"truncateString alone would not split one and the rune-boundary trim "+
						"is never exercised", stderrFixtureCap, len(capture))
				}
			},
			check: func(t *testing.T, capture, back string) {
				// A RESTATEMENT, not coverage for any mis-implementation. Measured:
				// the read-back is valid UTF-8 under every one of them, because
				// that same U+FFFD substitution happens on the way to disk — a
				// split rune surfaces as a length and prefix violation, never as an
				// invalid one. It is carried because it names the failure mode the
				// range check below actually detects.
				if !utf8.ValidString(back) {
					t.Errorf("#1700: the %d-byte read-back is not valid UTF-8; the writer split a "+
						"rune", len(back))
				}
				if len(back) > stderrFixtureCap || len(back) < stderrFixtureCap-(utf8.UTFMax-1) {
					t.Errorf("#1700: a %d-byte multi-byte capture reads back at %d bytes, want "+
						"within [%d, %d]; encoding/json substitutes U+FFFD per invalid byte, so a "+
						"byte cap with no rune-boundary trim reads back OVER the cap it states",
						len(capture), len(back), stderrFixtureCap-(utf8.UTFMax-1), stderrFixtureCap)
				}
				if !strings.HasPrefix(capture, back) {
					t.Errorf("#1700: the %d-byte read-back (first bytes %q) is not a prefix of the "+
						"original; the writer rewrote content rather than trimming a split tail, "+
						"and a substituted U+FFFD is not in the original either",
						len(back), back[:min(16, len(back))])
				}
			},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			if tc.precheck != nil {
				tc.precheck(t, tc.capture)
			}

			// INSIDE the subtest. The fresh pointer per call is why
			// initControlFullRecord is a function and not a package-level var:
			// hoisting this to the parent makes the assignment below a -race data
			// race across two parallel subtests, which its doc comment predicts.
			rec := initControlFullRecord()
			rec.StderrCapture = tc.capture
			scanner := dropcapScanner{needles: dropcapFixedNeedles()}
			// A fresh tempdir per row, and not stylistic: both rows mint the SAME
			// filename from the same ClaudeVersion and the same Arm, so a shared
			// directory would have them overwrite each other's artifact under a
			// racing read-back.
			path := writeInitControlFixture(t, t.TempDir(), scanner, rec)

			// The no-mutation contract, checked BEFORE the read-back: the writer
			// caps a copy, so the caller's record still holds everything it held.
			//
			// Scoped to the capped field deliberately. writeInitControlFixture's
			// `out := *rec` is a shallow copy sharing every slice header with the
			// caller, sufficient today only because the sole mutation is to a
			// string field. No mis-implementation above violates the slice-valued
			// fields; the shallow-copy hazard is a note for whoever caps a slice
			// field later, not something to widen this check for.
			if len(rec.StderrCapture) != len(tc.capture) {
				t.Errorf("#1700: the writer left the caller's record at %d bytes, want the "+
					"original %d; it caps in place, so an assertion against the caller's record "+
					"compares a mutated value with its own decode and proves nothing",
					len(rec.StderrCapture), len(tc.capture))
			}

			data, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("#1700: read back the capped fixture for claude_version %q: %v",
					rec.ClaudeVersion, err)
			}

			// #1748's AC 2, and it rides HERE rather than in a test function of its
			// own because the claim is VACUOUS UNDER-CAP: json.MarshalIndent is
			// deterministic, so over a record the cap does not shorten, re-marshalling
			// the caller's record is byte-identical and the row separates nothing. It
			// discriminates only over an over-cap record, and this test carries the
			// only two.
			//
			// Re-deriving the scanned bytes by calling the step again is legitimate
			// precisely because of the two contracts asserted a few lines above and in
			// its own doc: the writer does not mutate rec, and the step makes no
			// filesystem call.
			//
			// SOLE RED for two mis-implementations that leave every other assertion in
			// this test green: a writer that produced the disk bytes by some route
			// other than the returned slice in a way that still decodes (json.Marshal
			// instead of json.MarshalIndent, or dropcapWriteRecord's append(blob,
			// '\n')); and the CAP MOVED AFTER THE SCAN, where the scanned bytes are the
			// uncapped marshal while the file is still correctly bounded, so every
			// length, prefix and UTF-8 check below passes.
			scanned := scanInitControlFixture(t, scanner, rec)
			if !bytes.Equal(data, scanned) {
				// Lengths and an offset, never the blobs — this test's "# Do not print
				// the capture" rule. The offset is publishable here and NOT in the
				// step's refusal: both blobs compared here have already passed the
				// scan, so an offset between them localises nothing a fixture does not
				// already commit.
				diff := 0
				for diff < len(data) && diff < len(scanned) && data[diff] == scanned[diff] {
					diff++
				}
				t.Errorf("#1748: the file holds %d bytes and the scan saw %d, first differing at "+
					"byte %d; the bytes committed must be exactly the bytes the deny-scan passed, "+
					"or the scan cleared a blob the file does not carry — and a cap applied after "+
					"the scan reads exactly like this while every bound assertion below stays green",
					len(data), len(scanned), diff)
			}
			var back initControlFixtureRecord
			if err := json.Unmarshal(data, &back); err != nil {
				t.Fatalf("#1700: decode the capped fixture for claude_version %q: %v",
					rec.ClaudeVersion, err)
			}
			tc.check(t, tc.capture, back.StderrCapture)
		})
	}
}
